using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using Timelapse.Constant;
using Timelapse.Controls;
using Timelapse.Database;
using Timelapse.DataStructures;
using Timelapse.DataTables;
using Timelapse.DebuggingSupport;
using Timelapse.Enums;
using Timelapse.Util;

namespace Timelapse.Dialog
{
    public partial class DateTimeRereadFromFiles
    {
        #region Private Variables
        private readonly FileDatabase fileDatabase;

        // Tracks whether any changes to the database was made
        private bool IsAnyDataUpdated;

        // To help determine periodic updates to the progress bar 
        private DateTime lastRefreshDateTime = DateTime.Now;
        #endregion

        #region Constructor, Closing, AutoGenerated
        public DateTimeRereadFromFiles(Window owner, FileDatabase fileDatabase) : base(owner)
        {
            // Check the arguments for null 
            ThrowIf.IsNullArgument(fileDatabase, nameof(fileDatabase));

            InitializeComponent();

            this.fileDatabase = fileDatabase;

            // Tracks whether any changes to the data or database are made
            IsAnyDataUpdated = false;
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            FormattedDialogHelper.SetupStaticReferenceResolver(Message);
            this.Message.BuildContentFromProperties();
            // Set up a progress handler that will update the progress bar
            InitalizeProgressHandler(BusyCancelIndicator);
        }

        private void Window_Closing(object sender, CancelEventArgs e)
        {
            DialogResult = Token.IsCancellationRequested || IsAnyDataUpdated;
        }

        // Label and size the datagrid column headers
        private void DatagridFeedback_AutoGeneratedColumns(object sender, EventArgs e)
        {
            FeedbackGrid.Columns[0].Header = "File name (only for files whose date differs)";
            FeedbackGrid.Columns[0].Width = new(1, DataGridLengthUnitType.Auto);
            FeedbackGrid.Columns[1].Header = "Old date → New Date_ if it differs";
            FeedbackGrid.Columns[1].Width = new(2, DataGridLengthUnitType.Star);
        }
        #endregion

        #region Calculate times and Update files
        private async Task<ObservableCollection<DateTimeFeedbackTuple>> TaskRereadDatesAsync()
        {
            // A side effect of running this task is that the FileTable will be updated, which means that,
            // at the very least, the calling function will need to run FilesSelectAndShow to either
            // reload the FileTable with the updated data, or to reset the FileTable back to its original form
            // if the operation was cancelled.
            IsAnyDataUpdated = true;

            // Reread the Date_/Times from each file 
            return await Task.Run(() =>
            {
                ObservableCollection<DateTimeFeedbackTuple> feedbackRows = [];

                // Pass 1. For each file, check to see what dates/times need updating.
                Progress.Report(new(0, "Pass 1: Examining image and video dates...", true, false));
                int count = fileDatabase.CountAllCurrentlySelectedFiles;

                // Get the list of image rows (files) whose dates have changed
                List<ImageRow> filesToAdjust = GetImageRowsWithChangedDates(Progress, count, feedbackRows, out int missingFiles);

                // We are done if the operation has been cancelled, or there are no files with changed dates.
                if (CheckIfAllDone(filesToAdjust, feedbackRows, missingFiles))
                {
                    return feedbackRows;
                }

                // Pass 2. Update files in the database
                // Provide feedback that we are in the second pass, disabling the Cancel button in the progress bar as we shouldn't cancel half-way through a database update.
                string message = $"Pass 2: Updating {filesToAdjust.Count} files. Please wait...";
                Progress.Report(new(100, message, false, true));
                Thread.Sleep(ThrottleValues.RenderingBackoffTime);  // Allow the UI to update.

                //// Update the database
                DatabaseUpdateFileDates(filesToAdjust);

                // Provide summary feedback 
                message = $"Updated {filesToAdjust.Count}/{count} files whose dates have changed.";
                feedbackRows.Insert(0, (new("---", message)));
                if (missingFiles > 0)
                {
                    message = (missingFiles == 1)
                    ? $"{missingFiles} file is missing, and was not examined."
                    : $"{missingFiles} files are missing, and were not examined.";
                    feedbackRows.Insert(1, (new("---", message)));
                }
                return feedbackRows;
            }, Token).ConfigureAwait(continueOnCapturedContext: true); // Set to true as we need to continue in the UI context
        }

        // Returns:
        // - the list of files whose dates have changed
        // - a collection of feedback information for each file whose dates were changed, each row detailing the file name and how the dates were changed
        // - the number of missing Files, if any
        private List<ImageRow> GetImageRowsWithChangedDates(IProgress<ProgressBarArguments> progress, int count, ObservableCollection<DateTimeFeedbackTuple> feedbackRows, out int missingFiles)
        {
            List<ImageRow> filesToAdjust = [];
            missingFiles = 0;
            for (int fileIndex = 0; fileIndex < count; ++fileIndex)
            {
                if (Token.IsCancellationRequested)
                {
                    // A cancel was requested. Clear all pending changes and abort
                    feedbackRows.Clear();
                    break;
                }

                // We will store the various times here
                ImageRow file = fileDatabase.FileTable[fileIndex];
                DateTime originalDateTime = file.DateTimeIncorporatingOffsetPLAINVERSION;
                string feedbackMessage = string.Empty;

                try
                {
                    // Get the image (if its there), get the new dates/times, and add it to the list of images to be updated 
                    // Note that if the image can't be created, we will just to the catch.
                    bool usingMetadataTimestamp = true;
                    if (file.FileExists(fileDatabase.RootPathToImages) == false)
                    {
                        // The file does not exist. Generate a feedback message
                        missingFiles++;
                    }
                    else
                    {
                        // Read the date from the file, and check to see if its different from the recorded date
                        DateTimeAdjustmentEnum dateTimeAdjustment = file.TryReadDateTimeOriginalFromMetadata(fileDatabase.RootPathToImages);
                        if (dateTimeAdjustment == DateTimeAdjustmentEnum.MetadataNotUsed)
                        {
                            // We couldn't read the metadata, so get a candidate date/time from the file info instead
                            file.SetDateTimeFromFileInfo(fileDatabase.RootPathToImages);
                            usingMetadataTimestamp = false;
                        }
                        DateTime rescannedDateTime = file.DateTimeIncorporatingOffsetPLAINVERSION;
                        bool sameDate = rescannedDateTime.Date == originalDateTime.Date;
                        bool sameTime = rescannedDateTime.TimeOfDay == originalDateTime.TimeOfDay;

                        if (!(sameDate && sameTime))
                        {
                            // Date has been updated - add it to the queue of files to be processed, and generate a feedback message.
                            filesToAdjust.Add(file);
                            feedbackMessage = "\x2713"; // Checkmark 
                            feedbackMessage += DateTimeHandler.ToStringDisplayDateTime(originalDateTime) + " \x2192 " + DateTimeHandler.ToStringDisplayDateTime(rescannedDateTime);
                            feedbackMessage += usingMetadataTimestamp ? " (read from metadata)" : " (read from file)";
                            feedbackRows.Add(new(file.File, feedbackMessage));
                        }
                    }
                }
                catch (Exception exception)
                {
                    // This shouldn't happen, but just in case. 
                    TracePrint.PrintMessage(
                        $"Unexpected exception processing '{file.File}' in DateTimeReread. {exception}");
                    feedbackMessage += $"✖ skipping: {exception.Message}";
                    feedbackRows.Add(new(file.File, feedbackMessage));
                    break;
                }

                // Update the progress bar every time interval to indicate what file we are working on
                TimeSpan intervalFromLastRefresh = DateTime.Now - lastRefreshDateTime;
                if (intervalFromLastRefresh > ThrottleValues.ProgressBarRefreshInterval)
                {
                    int percentDone = Convert.ToInt32(fileIndex / Convert.ToDouble(count) * 100.0);
                    progress.Report(new(percentDone,
                        $"Pass 1: Checking dates for {fileIndex} / {count} files", true, false));
                    Thread.Sleep(ThrottleValues.RenderingBackoffTime);
                    lastRefreshDateTime = DateTime.Now;
                }
            }
            return filesToAdjust;
        }

        // We are done if the operation has been cancelled, or there are no files with changed dates.
        private bool CheckIfAllDone(List<ImageRow> filesToAdjust, ObservableCollection<DateTimeFeedbackTuple> feedbackRows, int missingFiles)
        {
            string message;
            // Abort (with feedback) if no dates needed changing and no cancellation request is pending
            if (filesToAdjust.Count <= 0 && Token.IsCancellationRequested == false)
            {
                // None of the file dates need updating, so no need to do anything more.
                message = "No files updated as their dates have not changed.";
                feedbackRows.Add(new("---", message));

                if (missingFiles > 0)
                {
                    message = (missingFiles == 1)
                    ? $"{missingFiles} file is missing, and was not examined."
                    : $"{missingFiles} files are missing, and were not examined.";
                    feedbackRows.Add(new("---", message));
                }
                return true;
            }

            // Abort (with feedback) the operation was cancelled
            if (Token.IsCancellationRequested)
            {
                feedbackRows.Clear();
                message = "No changes were made";
                feedbackRows.Add(new("Cancelled", message));
                return true;
            }
            return false;
        }

        // Update dates in the database for the given image rows 
        private void DatabaseUpdateFileDates(List<ImageRow> filesToAdjust)
        {
            // Update the database
            List<ColumnTuplesWithWhere> imagesToUpdate = [];
            foreach (ImageRow image in filesToAdjust)
            {
                imagesToUpdate.Add(image.GetDateTimeColumnTuples());
            }
            fileDatabase.UpdateFiles(imagesToUpdate);  // Write the updates to the database
        }
        #endregion

        #region Button callbacks
        // Set up the UI and invoke the Reread
        private async void StartButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                await StartButton_ClickAsync();
            }
            catch (Exception ex)
            {
                TracePrint.CatchException(ex.Message);
            }
        }

        private async Task StartButton_ClickAsync()
        {
            // ConfigureFormatForDateTimeCustom the UI's initial state
            CancelButton.IsEnabled = false;
            CancelButton.Visibility = Visibility.Hidden;
            StartDoneButton.Content = "_Done";
            StartDoneButton.Click -= StartButton_Click;
            StartDoneButton.Click += DoneButton_Click;
            StartDoneButton.IsEnabled = false;
            BusyCancelIndicator.IsBusy = true;
            WindowCloseButtonIsEnabled(false);

            // Reread the Date_/Times from each file
            // feedbackRows will hold key / value pairs that will be bound to the datagrid feedback,
            // which is the way to make those pairs appear in the data grid during background worker progress updates
            // The progress bar will be displayed during this process.
            ObservableCollection<DateTimeFeedbackTuple> feedbackRows = await TaskRereadDatesAsync().ConfigureAwait(true);

            // Hide the busy indicator and update the UI, e.g., to show which files have changed dates
            BusyCancelIndicator.IsBusy = false;
            FeedbackGrid.Visibility = Visibility.Visible;
            FeedbackGrid.ItemsSource = feedbackRows;
            StartDoneButton.IsEnabled = true;
            WindowCloseButtonIsEnabled(true);
        }

        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
        }

        private void DoneButton_Click(object sender, RoutedEventArgs e)
        {
            // We return false if the database was not altered, i.e., if this was all a no-op
            DialogResult = IsAnyDataUpdated;
        }
        #endregion
    }
}
