using System;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using Timelapse.Constant;
using Timelapse.Controls;
using Timelapse.Database;
using Timelapse.DataStructures;
using Timelapse.DataTables;
using Timelapse.DebuggingSupport;
using Timelapse.Util;

namespace Timelapse.Dialog
{
    /// <summary>
    /// This dialog lets a user enter a time change correction of +/-1 hour, which is propagated backwards/forwards.
    /// The current image as set by the user in the radio buttons.
    /// </summary>
    public partial class DateDaylightSavingsTimeCorrection
    {
        #region Private Variables
        private readonly int currentImageRow;
        private readonly FileDatabase fileDatabase;
        private readonly FileTableEnumerator fileEnumerator;

        // Tracks whether any changes to the data or database are made
        private bool IsAnyDataUpdated;
        #endregion

        #region Constructor, Loaded, AutoGeneration, and Closing
        public DateDaylightSavingsTimeCorrection(Window owner, FileDatabase database, FileTableEnumerator fileEnumerator) : base(owner)
        {
            // Check the arguments for null 
            ThrowIf.IsNullArgument(database, nameof(database));
            ThrowIf.IsNullArgument(fileEnumerator, nameof(fileEnumerator));

            InitializeComponent();
            fileDatabase = database;
            this.fileEnumerator = fileEnumerator;
            currentImageRow = fileEnumerator.CurrentRow;
        }

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            FormattedDialogHelper.SetupStaticReferenceResolver(Message);
            this.Message.BuildContentFromProperties();
            // Set up a progress handler that will update the progress bar
            InitalizeProgressHandler(BusyCancelIndicator);

            // Get the original date and display it
            if (fileEnumerator.Current == null)
            {
                // Shouldn't happen. I'm not sure what would happen if this bungs up, but at least we will get a message.
                TracePrint.NullException(nameof(fileEnumerator.Current));
                return;
            }
            OriginalDate.Content = fileEnumerator.Current.DateTimeAsDisplayable;
            NewDate.Content = OriginalDate.Content;

            // Display the image. While we should be on a valid image (our assumption), we can still show a missing or corrupted image if needed
            Image.Source = fileEnumerator.Current.LoadBitmap(fileDatabase.RootPathToImages, out _);
            FileName.Content = fileEnumerator.Current.File;
            FileName.ToolTip = FileName.Content;
        }

        private void Window_Closing(object sender, CancelEventArgs e)
        {
            DialogResult = Token.IsCancellationRequested || IsAnyDataUpdated;
        }

        // Label and size the datagrid column headers
        private void DatagridFeedback_AutoGeneratedColumns(object sender, EventArgs e)
        {
            FeedbackGrid.Columns[0].Header = "File name (only for files whose date was changed)";
            FeedbackGrid.Columns[0].Width = new(1, DataGridLengthUnitType.Auto);
            FeedbackGrid.Columns[1].Header = "Old date  \x2192  New Date \x2192 Delta";
            FeedbackGrid.Columns[1].Width = new(2, DataGridLengthUnitType.Star);
        }
        #endregion

        #region Calculate times and Update files
        // Set up all the Linear Corrections as an asynchronous task which updates the progress bar as needed
        private async Task<ObservableCollection<DateTimeFeedbackTuple>> TaskDaylightSavingsCorrectionAsync(TimeSpan adjustment, int startRow, int endRow)
        {
            // A side effect of running this task is that the FileTable will be updated, which means that,
            // at the very least, the calling function will need to run FilesSelectAndShow to either
            // reload the FileTable with the updated data, or to reset the FileTable back to its original form
            // if the operation was cancelled.
            IsAnyDataUpdated = true;

            // Reread the Date/Times from each file 
            return await Task.Run(() =>
            {
                // Collects feedback to display in a datagrid after the operation is done
                ObservableCollection<DateTimeFeedbackTuple> feedbackRows = [];

                DatabaseUpdateFileDates(Progress, adjustment, startRow, endRow, feedbackRows);

                // Provide feedback if the operation was cancelled during the database update
                if (Token.IsCancellationRequested)
                {
                    feedbackRows.Clear();
                    feedbackRows.Add(new("Cancelled", "No changes were made"));
                    return feedbackRows;
                }
                return feedbackRows;
            }, Token).ConfigureAwait(continueOnCapturedContext: true); // Set to true as we need to continue in the UI context
        }

        private void DatabaseUpdateFileDates(IProgress<ProgressBarArguments> progress, TimeSpan adjustment, int startRow, int endRow, ObservableCollection<DateTimeFeedbackTuple> feedbackRows)
        {
            // Note that this passes a function which is invoked by the fileDatabase method. 
            // This not only calculates the new times, but updates the progress bar as the fileDatabase method iterates through the files.
            // this.fileDatabase.AdjustFileTimes(daylightSavingsAdjustment, startRow, endRow); // For all rows...
            fileDatabase.UpdateAdjustedFileTimes(
               (fileName, fileIndex, count, imageDateTime) =>
               {
                   if (adjustment.Duration() >= TimeSpan.FromSeconds(1))
                   {
                       // We only add to the feedback row if the change duration is > 1 second, as otherwise we don't change it.
                       string oldDT = DateTimeHandler.ToStringDisplayDateTime(imageDateTime);
                       string newDT = DateTimeHandler.ToStringDisplayDateTime(imageDateTime + adjustment);
                       feedbackRows.Add(new(fileName, oldDT + " \x2192 " + newDT + " \x2192 " + PrettyPrintTimeAdjustment(adjustment)));
                   }

                   // Update the progress bar every time interval to indicate what file we are working on
                   if (ReadyToRefresh())
                   {
                       int percentDone = Convert.ToInt32(fileIndex / Convert.ToDouble(count) * 100.0);
                       progress.Report(new(percentDone,
                           $"Pass 1: Calculating new date/times for {fileIndex} / {count} files", true, false));
                       Thread.Sleep(ThrottleValues.RenderingBackoffTime);  // Allows the UI thread to update every now and then
                   }

                   if (fileIndex >= count)
                   {
                       // After all files are processed, the next step would be updating the database. Disable the cancel button too.
                       // This really should be somehow signalled from the invoking method (ideally ExecuteNonQueryWrappedInBeginEnd every update interval), but this is a reasonable workaround.
                       progress.Report(new(100,
                           $"Pass 2: Updating {feedbackRows.Count} files. Please wait...", false, true));
                       Thread.Sleep(ThrottleValues.RenderingBackoffTime);  // Allows the UI thread to update every now and then
                   }
                   return imageDateTime + adjustment; // Returns the new time
               },
               startRow,
               endRow, //this.fileDatabase.CurrentlySelectedFileCount - 1,
               Token);
        }

        #endregion

        #region Callback - Start Button
        // When the user clicks ok, add/subtract an hour propagated forwards/backwards as specified
        private async void StartButton_Click(object sender, RoutedEventArgs e)
        {
            // We have a valide new time that differs by at least one second.
            // ConfigureFormatForDateTimeCustom the UI's initial state
            CancelButton.IsEnabled = false;
            CancelButton.Visibility = Visibility.Hidden;
            StartDoneButton.Content = "_Done";
            StartDoneButton.Click -= StartButton_Click;
            StartDoneButton.Click += DoneButton_Click;
            StartDoneButton.IsEnabled = false;
            BusyCancelIndicator.IsBusy = true;
            WindowCloseButtonIsEnabled(false);

            // Calculate the required adjustment
            bool forward = rbForward.IsChecked == true;
            int startRow;
            int endRow;
            if (forward)
            {
                startRow = currentImageRow;
                endRow = fileDatabase.CountAllCurrentlySelectedFiles - 1;
            }
            else
            {
                startRow = 0;
                endRow = currentImageRow;
            }

            // Update the database
            int hours = rbAddHour.IsChecked == true? 1 : -1;
            TimeSpan daylightSavingsAdjustment = new(hours, 0, 0);

            // This call does all the actual updating...
            ObservableCollection<DateTimeFeedbackTuple> feedbackRows = await TaskDaylightSavingsCorrectionAsync(daylightSavingsAdjustment, startRow, endRow).ConfigureAwait(true);

            // Hide the busy indicator and update the UI, e.g., to show which files have changed dates
            // Provide summary feedback 
            if (IsAnyDataUpdated && Token.IsCancellationRequested == false)
            {
                string message =
                    $"Updated {feedbackRows.Count}/{fileDatabase.CountAllCurrentlySelectedFiles} files whose dates have changed.";
                feedbackRows.Insert(0, (new("---", message)));
            }

            BusyCancelIndicator.IsBusy = false;
            PrimaryPanel.Visibility = Visibility.Collapsed;
            Image.Visibility = Visibility.Collapsed;
            FeedbackGrid.ItemsSource = feedbackRows;
            FeedbackPanel.Visibility = Visibility.Visible;
            StartDoneButton.IsEnabled = true;
            WindowCloseButtonIsEnabled(true);
        }
        #endregion

        #region Callback - Checkboxes
        // Examine the checkboxes to see what state our selection is in, and provide feedback as appropriate
        private void RadioButton_Checked(object sender, RoutedEventArgs e)
        {
            if (rbAddHour.IsChecked == true || rbSubtractHour.IsChecked == true)
            {
                if (DateTimeHandler.TryParseDisplayDateTime((string)OriginalDate.Content, out DateTime dateTime) == false)
                {
                    NewDate.Content = "Problem with this date...";
                    StartDoneButton.IsEnabled = false;
                    return;
                }
                int hours = rbAddHour.IsChecked == true ? 1 : -1;
                TimeSpan daylightSavingsAdjustment = new(hours, 0, 0);
                dateTime = dateTime.Add(daylightSavingsAdjustment);
                NewDate.Content = DateTimeHandler.ToStringDisplayDateTime(dateTime);
            }
            if ((rbAddHour.IsChecked == true || rbSubtractHour.IsChecked == true) && (rbBackwards.IsChecked == true || rbForward.IsChecked == true))
            {
                StartDoneButton.IsEnabled = true;
            }
            else
            {
                StartDoneButton.IsEnabled = false;
            }
        }
        #endregion

        #region  Callbacks - Dialog Button
        private void DoneButton_Click(object sender, RoutedEventArgs e)
        {
            // We return true if the database was altered but also if there was a cancellation, as a cancelled operation
            // will likely have changed the FileTable (but not database) date entries. Returning true will reset them, as a FileSelectAndShow will be done.
            // Kinda hacky as it expects a certain behaviour of the caller, but it works.
            DialogResult = Token.IsCancellationRequested || IsAnyDataUpdated;
        }

        // Cancel - do nothing
        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
        }
        #endregion

        #region Utility methods
        // Given the time adjustment to the date, generate a pretty-printed string that we can use in our feedback
        private static string PrettyPrintTimeAdjustment(TimeSpan adjustment)
        {
            string sign = (adjustment < TimeSpan.Zero) ? "-" : "+";

            // Pretty print the adjustment time, depending upon how many day(s) were included 
            string format;
            if (adjustment.Days == 0)
            {
                format = "{0:s}{1:D2}:{2:D2}:{3:D2}"; // Don't show the days field
            }
            else
            {
                // includes singular or plural form of days
                format = (adjustment.Duration().Days == 1) ? "{0:s}{1:D2}:{2:D2}:{3:D2} {0:s} {4:D} day" : "{0:s}{1:D2}:{2:D2}:{3:D2} {0:s} {4:D} days";
            }
            return string.Format(format, sign, adjustment.Duration().Hours, adjustment.Duration().Minutes, adjustment.Duration().Seconds, adjustment.Duration().Days);
        }
        #endregion
    }
}
