using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Windows;
using System.Windows.Input;
using Timelapse.Constant;
using Timelapse.Database;
using Timelapse.DataStructures;
using Timelapse.DataTables;
using Timelapse.Util;

namespace Timelapse.Dialog
{
    /// <summary>
    /// Interaction logic for FileMetadataPopulateAllOnLoad.xaml
    /// </summary>
    public partial class FileMetadataPopulateAllOnLoad
    {
        #region Private variables
        // Passed in parameters
        private string FilePath;
        private readonly FileDatabase FileDatabase;
        #endregion

        #region Public variables
        // Return a data structure containing a list of key value pairs that define the selected metadata and data label
        public ImageMetadataOnLoad ImageMetadataOnLoad = new();
        #endregion

        #region Initialization
        public FileMetadataPopulateAllOnLoad(Window owner, FileDatabase fileDatabase, string filePath)
        {
            InitializeComponent();
            FormattedDialogHelper.SetupStaticReferenceResolver(Message);
            FilePath = filePath;
            FileDatabase = fileDatabase;
            Owner = owner;
        }
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            this.Message.BuildContentFromProperties();
            Dialogs.TryPositionAndFitDialogIntoWindow(this);
            Mouse.OverrideCursor = null;

            MetadataGrid.viewModel.RootPath = FileDatabase.RootPathToDatabase;
            MetadataGrid.viewModel.FilePath = FilePath;

            // Construct a dictionary of the available data fields
            // Include Note, MultiLine, numeric types, Flag, and DateTime types
            // The FileMetadataGrid will filter these per-row based on metadata value type
            // Exclude certain system fields that should not be populated from metadata on load
            Dictionary<string, string> collectLabels = [];
            Dictionary<string, string> collectControlTypes = [];
            Dictionary<string, Choices> collectChoices = [];
            foreach (ControlRow control in FileDatabase.Controls)
            {
                // Skip controls with DataLabels: File, RelativePath, DateTime, DeleteFlag
                if (control.DataLabel == DatabaseColumn.File ||
                    control.DataLabel == DatabaseColumn.RelativePath ||
                    control.DataLabel == DatabaseColumn.DateTime ||
                    control.DataLabel == DatabaseColumn.DeleteFlag)
                {
                    continue;
                }

                collectLabels.Add(control.DataLabel, control.Label);
                collectControlTypes.Add(control.DataLabel, control.Type);

                // For FixedChoice and MultiChoice controls, parse and store the choices
                if (control.Type == Constant.Control.FixedChoice || control.Type == Constant.Control.MultiChoice)
                {
                    Choices choices = Choices.ChoicesFromJson(control.List);
                    collectChoices.Add(control.DataLabel, choices);
                }
            }

            // Setting DictDataLabel_Label will result in desired side effects in the FileMetadataGrid user control
            MetadataGrid.DictDataLabel_Label = collectLabels;
            MetadataGrid.SetControlTypeMapping(collectControlTypes);
            MetadataGrid.SetChoicesMapping(collectChoices);
            MetadataGrid.SelectedMetadata.CollectionChanged += SelectedMetadata_CollectionChanged;
        }

        // This datagrid will indicate, for the selected metadata, the metadata values assigned to the selected field
        private void FeedbackDatagrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            FeedbackGrid.Columns[0].Header = "File Name";
            FeedbackGrid.Columns[1].Header = "Metadata name";
            FeedbackGrid.Columns[2].Header = "Metadata Value";
        }
        #endregion

        #region Change Notifications
        private void SelectedMetadata_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            // Enable or disable the Populate button to match if any items are in the selectedMetadataList 
            DoneButton.IsEnabled = MetadataGrid.SelectedMetadata is { Count: > 0 };
        }
        #endregion

        #region Button callbacks
        private void OpenFile_Click(object sender, RoutedEventArgs e)
        {
            string filter = String.Format("Images and videos (*{0};*{1};*{2};*{3};*{4})|*{0};*{1};*{2};*{3};*{4}", File.JpgFileExtension, File.AviFileExtension, File.Mp4FileExtension, File.ASFFileExtension, File.MovFileExtension);
            if (Dialogs.TryGetFileFromUserUsingOpenFileDialog("Select a typical file to inspect", ".", filter, File.JpgFileExtension, out string filePath))
            {
                FilePath = filePath;
                MetadataGrid.viewModel.RootPath = FileDatabase.RootPathToDatabase;
                MetadataGrid.viewModel.FilePath = FilePath;
                MetadataGrid.Refresh();
            }
        }
        private void Done_Click(object sender, RoutedEventArgs e)
        {
            ImageMetadataOnLoad.SelectedImageMetadataDataLabels = MetadataGrid.SelectedMetadata.ToList();
            ImageMetadataOnLoad.MetadataToolSelected = MetadataGrid.MetadataToolSelected;
            DialogResult = true;
        }
        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
        }
        #endregion
    }
}

