using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using Timelapse.Constant;
using Timelapse.ControlsDataEntry;
using Timelapse.Database;
using Timelapse.DataStructures;
using Timelapse.DataTables;
using Timelapse.Enums;
using Timelapse.Util;

namespace Timelapse.Dialog
{
    /// <summary>
    /// Dialog for populating date/time fields from metadata.
    /// Only allows populating DateTime, Date, and Time controls.
    /// </summary>
    public partial class FileMetadataPopulateDatesOnly
    {
        #region Constructor
        public FileMetadataPopulateDatesOnly(Window owner, FileDatabase fileDatabase, DataEntryHandler dataHandler, string filePath)
            : base(owner, fileDatabase, dataHandler, filePath)
        {
            InitializeComponent();
            FormattedDialogHelper.SetupStaticReferenceResolver(DatesOnlyMessage);
        }
        #endregion

        #region Abstract method implementations
        protected override Task<ObservableCollection<FileMetadataFeedbackRow>> PopulateMetadataAsync(Enums.MetadataToolEnum metadataToolSelected, bool previewOnly)
            => PopulateDatesAsync(metadataToolSelected, previewOnly);

        protected override System.Windows.Controls.DataGrid GetFeedbackGrid() => FeedbackGrid;
        protected override System.Windows.Controls.Panel GetFeedbackPanel() => FeedbackPanel;
        protected override Controls.FileMetadataGrid GetMetadataGrid() => MetadataGrid;
        protected override Controls.BusyCancelIndicator GetBusyCancelIndicator() => BusyCancelIndicator;
        protected override System.Windows.Controls.TextBlock GetPopulatingMessage() => PopulatingMessage;
        protected override System.Windows.Controls.Button GetStartDoneButton() => StartDoneButton;
        protected override System.Windows.Controls.Button GetPreviewButton() => PreviewButton;
        protected override System.Windows.Controls.Button GetBackButton() => BackButton;
        protected override System.Windows.Controls.Button GetCancelButton() => CancelButton;
        protected override System.Windows.Controls.RadioButton GetShowEverythingRadioButton() => ShowEverythingRadioButton;

        protected override void ShowHideDialogSpecificElements(bool showMetadataGrid)
        {
            // This dialog has no additional elements to show/hide
        }

        protected override string GetPreviewCompletedMessage()
        {
            return "Preview of date/time population (no changes made to database).";
        }
        #endregion

        #region Window event handlers
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            DatesOnlyMessage.BuildContentFromProperties();

            // Set up progress handler
            InitializeProgressHandler(BusyCancelIndicator);

            // Configure the metadata grid
            MetadataGrid.viewModel.RootPath = FileDatabase.RootPathToDatabase;
            MetadataGrid.viewModel.FilePath = FilePath;
            MetadataGrid.ImageMetadataFilter = ImageMetadataFiltersEnum.DatesOnly;

            // Construct a dictionary of the available date/time fields as labels|datalabels
            Dictionary<string, string> collectLabels = [];
            Dictionary<string, string> collectControlTypes = [];
            foreach (ControlRow control in FileDatabase.Controls)
            {
                if (control.Type == DatabaseColumn.DateTime || control.Type == Control.DateTime_ ||
                    control.Type == Control.Date_ || control.Type == Control.Time_)
                {
                    // Only include DateTime/Date/Time controls
                    collectLabels.Add(control.DataLabel, control.Label);
                    collectControlTypes.Add(control.DataLabel, control.Type);
                }
            }

            // Setting DictDataLabel_Label will result in desired side effects in the FileMetadataGrid user control
            MetadataGrid.DictDataLabel_Label = collectLabels;
            MetadataGrid.SetControlTypeMapping(collectControlTypes);
            MetadataGrid.SelectedMetadata.CollectionChanged += SelectedMetadata_CollectionChanged;
        }

        // Window_Closing, FeedbackDatagrid_AutoGeneratedColumns, and FeedbackDisplayRadioButton_Changed are in base class
        #endregion

        #region Change Notifications
        private void SelectedMetadata_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            // Enable or disable the Populate and Preview buttons to match if any items are in the selectedMetadataList
            bool hasSelection = MetadataGrid.SelectedMetadata is { Count: > 0 };
            StartDoneButton.IsEnabled = hasSelection;
            PreviewButton.IsEnabled = hasSelection;
        }
        #endregion

        #region Button callbacks - implemented in base class
        // Preview_Click, Start_Click, Back_Click, Done_Click, CancelButton_Click are in FileMetadataPopulateBase
        #endregion

        #region Populate dates from metadata
        private async Task<ObservableCollection<FileMetadataFeedbackRow>> PopulateDatesAsync(MetadataToolEnum metadataToolSelected, bool previewOnly = false)
        {
            ObservableCollection<FileMetadataFeedbackRow> feedbackData = [];

            if (MetadataGrid.SelectedMetadata.Count == 0)
            {
                feedbackData.Clear();
                feedbackData.Add(new("Nothing was selected", "", "No changes were made", isSuccessRow: false));
                return feedbackData;
            }

            return await Task.Run(() =>
            {
                List<ColumnTuplesWithWhere> imagesToUpdate = [];
                double totalImages = FileDatabase.CountAllCurrentlySelectedFiles;
                string[] tags = MetadataGrid.SelectedTags;

                for (int imageIndex = 0; imageIndex < totalImages; ++imageIndex)
                {
                    if (IsCancellationRequested())
                    {
                        feedbackData.Clear();
                        feedbackData.Add(new("Cancelled", "", "No changes were made", isSuccessRow: false));
                        return feedbackData;
                    }

                    ImageRow image = FileDatabase.FileTable[imageIndex];

                    var metadata = metadataToolSelected == MetadataToolEnum.MetadataExtractor
                        ? ImageMetadataDictionary.LoadMetadata(image.GetFilePath(FileDatabase.RootPathToImages))
                        : MetadataGrid.ExifToolManager.FetchExifFrom(image.GetFilePath(FileDatabase.RootPathToImages), tags);

                    if (IsReadyToRefresh())
                    {
                        int percentDone = Convert.ToInt32(imageIndex / totalImages * 100.0);
                        ReportProgress(new(percentDone, $"{imageIndex}/{totalImages} images. Processing {image.File}", true, false));
                        Thread.Sleep(ThrottleValues.RenderingBackoffTime);
                    }

                    foreach (var item in MetadataGrid.SelectedMetadata)
                    {
                        string metadataTag = item.MetadataTag;
                        string dataLabelToUpdate = item.DataLabel;
                        string controlType = item.Type;

                        if (!metadata.TryGetValue(metadataTag, out var value))
                        {
                            feedbackData.Add(new(image.File, metadataTag, "⚠No metadata found - data field unchanged", isSuccessRow: false));
                            continue;
                        }

                        string metadataValue = value.Value;
                        if (!DateTimeHandler.TryParseMetadataDateTaken(metadataValue, out DateTime metadataDateTime))
                        {
                            feedbackData.Add(new(image.File, metadataTag, $"⚠Data field unchanged - '{metadataValue}' is not a valid date/time.", isSuccessRow: false));
                            continue;
                        }

                        string dateTimeStringToUse = string.Empty;

                        if (dataLabelToUpdate == DatabaseColumn.DateTime)
                        {
                            dateTimeStringToUse = DateTimeHandler.ToStringDatabaseDateTime(metadataDateTime);
                            if (!previewOnly)
                            {
                                image.SetDateTime(metadataDateTime);
                                ColumnTuplesWithWhere imageUpdate = image.GetDateTimeColumnTuples();
                                imagesToUpdate.Add(imageUpdate);
                            }
                            feedbackData.Add(new(image.File, metadataTag, dateTimeStringToUse, isSuccessRow: true));
                        }
                        else
                        {
                            // controlType is already available from item.Type above
                            if (controlType == Control.DateTime_)
                            {
                                dateTimeStringToUse = DateTimeHandler.ToStringDatabaseDateTime(metadataDateTime);
                            }
                            else if (controlType == Control.Date_)
                            {
                                dateTimeStringToUse = DateTimeHandler.ToStringDatabaseDate(metadataDateTime);
                            }
                            else if (controlType == Control.Time_)
                            {
                                dateTimeStringToUse = DateTimeHandler.ToStringTime(metadataDateTime);
                            }

                            if (!string.IsNullOrEmpty(dateTimeStringToUse))
                            {
                                if (!previewOnly)
                                {
                                    ColumnTuplesWithWhere imageUpdate = new([new(dataLabelToUpdate, dateTimeStringToUse)], image.ID);
                                    imagesToUpdate.Add(imageUpdate);
                                }
                                feedbackData.Add(new(image.File, metadataTag, metadataValue, isSuccessRow: true));
                            }
                            else
                            {
                                feedbackData.Add(new(image.File, metadataTag, $"⚠Data field unchanged - '{metadataValue}' is not a valid date/time.", isSuccessRow: false));
                            }
                        }
                    }
                }

                if (!previewOnly)
                {
                    isAnyDataUpdated = true;
                    ReportProgress(new(100, $"Writing metadata for {totalImages} files. Please wait...", false, true));
                    Thread.Sleep(ThrottleValues.RenderingBackoffTime);
                    FileDatabase.UpdateFiles(imagesToUpdate);
                }
                return feedbackData;
            }, GetCancellationToken()).ConfigureAwait(true);
        }
        #endregion
    }
}
