using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Windows;
using System.Windows.Input;
using Timelapse.Constant;
using Timelapse.Database;
using Timelapse.DataStructures;
using Timelapse.DataTables;
using Timelapse.Util;

namespace Timelapse.Dialog
{
    /// <summary>
    /// Interaction logic for PopulateFieldsWithImageMetadataOnLoad.xaml
    /// </summary>
    public partial class PopulateFieldsWithImageMetadataOnLoad
    {
        #region Private variables
        // Passed in parameters
        private string FilePath;
        private readonly FileDatabase FileDatabase;
        #endregion

        #region Public variables
        // Return a data structure containing a list of key value pairs that define the selected metadata and data label
        public ImageMetadataOnLoad ImageMetadataOnLoad = new();
        #endregion

        #region Initialization
        public PopulateFieldsWithImageMetadataOnLoad(Window owner, FileDatabase fileDatabase, string filePath)
        {
            InitializeComponent();
            FormattedDialogHelper.SetupStaticReferenceResolver(Message);
            FilePath = filePath;
            FileDatabase = fileDatabase;
            Owner = owner;
        }
        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            this.Message.BuildContentFromProperties();
            Dialogs.TryPositionAndFitDialogIntoWindow(this);
            Mouse.OverrideCursor = null;

            MetadataGrid.viewModel.FilePath = FilePath;

            // Construct a dictionary of the available note fields as labels|datalabels
            // and a list of only the note field labels which will be used to populate the ComboBoxes in the datagrid
            Dictionary<string, string> collectLabels = [];
            foreach (ControlRow control in FileDatabase.Controls)
            {
                if (control.Type == Control.Note)
                {
                    collectLabels.Add(control.DataLabel, control.Label);
                }
            }

            // Setting DictDataLabel_Label will result in desired updating side effects in the FileMetadataGrid user control
            MetadataGrid.DictDataLabel_Label = collectLabels;
            MetadataGrid.SelectedMetadata.CollectionChanged += SelectedMetadata_CollectionChanged;
        }

        // This datagrid will indicate, for the selected metadata, the metadata values assigned to the selected field
        private void FeedbackDatagrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            FeedbackGrid.Columns[0].Header = "File Name";
            FeedbackGrid.Columns[1].Header = "Metadata name";
            FeedbackGrid.Columns[2].Header = "Metadata Value";
        }
        #endregion

        #region Change Notifications
        private void SelectedMetadata_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            // Enable or disable the Populate button to match if any items are in the selectedMetadataList 
            DoneButton.IsEnabled = MetadataGrid.SelectedMetadata is { Count: > 0 };
        }
        #endregion

        #region Button callbacks
        private void OpenFile_Click(object sender, RoutedEventArgs e)
        {
            string filter = String.Format("Images and videos (*{0};*{1};*{2};*{3};*{4})|*{0};*{1};*{2};*{3};*{4}", File.JpgFileExtension, File.AviFileExtension, File.Mp4FileExtension, File.ASFFileExtension, File.MovFileExtension);
            if (Dialogs.TryGetFileFromUserUsingOpenFileDialog("Select a typical file to inspect", ".", filter, File.JpgFileExtension, out string filePath))
            {
                FilePath = filePath;
                MetadataGrid.viewModel.FilePath = FilePath;
                MetadataGrid.Refresh();
            }
        }
        private void Done_Click(object sender, RoutedEventArgs e)
        {
            ImageMetadataOnLoad.SelectedImageMetadataDataLabels = MetadataGrid.SelectedMetadata.ToList();
            ImageMetadataOnLoad.MetadataToolSelected = MetadataGrid.MetadataToolSelected;
            DialogResult = true;
        }
        private void CancelButton_Click(object sender, RoutedEventArgs e)
        {
            DialogResult = false;
        }
        #endregion
    }
}

