using System;
using System.Collections.Generic;
using Timelapse.Constant;

namespace TimelapseTemplateEditor.Standards
{
    public static class AlbertaMetadataStandard
    {
        // The AlbertaMetadataStandard standard specification:
        // - a list of StandardsRow,
        // - level aliases
        // - a list of common species (used by particular rows), 

        // Name of this standard
        public static string Standard = Timelapse.Constant.Standards.AlbertaMetadataStandard;

        #region The Alias specification associated with each level
        public static Dictionary<int, string> Aliases = new()
        {
            {1, "Project"},
            {2, "Study Area"},
            {3, "Survey"},
            {4, "Sample Station"},
            {5, "Deployment"}
        };

        #endregion

        #region List of common species
        public static List<string> SpeciesCommonList =
        [
            "ACADIAN FLYCATCHER",
            "ALDER FLYCATCHER",
            "AMERICAN AVOCET",
            "AMERICAN BISON",
            "AMERICAN BITTERN",
            "AMERICAN BLACK DUCK",
            "AMERICAN COOT",
            "AMERICAN CROW",
            "AMERICAN DIPPER",
            "AMERICAN GOLDEN-PLOVER",
            "AMERICAN GOLDFINCH",
            "AMERICAN KESTREL",
            "AMERICAN PIPIT",
            "AMERICAN REDSTART",
            "AMERICAN ROBIN",
            "AMERICAN SWALLOW-TAILED KITE",
            "AMERICAN TREE SPARROW",
            "AMERICAN WHITE PELICAN",
            "AMERICAN WIGEON",
            "AMERICAN WOODCOCK",
            "ANCIENT MURRELET",
            "ANNA'S HUMMINGBIRD",
            "ARCTIC FOX",
            "ARCTIC SHREW",
            "ARCTIC TERN",
            "BADGER",
            "BAIRD'S SANDPIPER",
            "BAIRD'S SPARROW",
            "BALD EAGLE",
            "BALTIMORE ORIOLE",
            "BAND-TAILED PIGEON",
            "BANK SWALLOW",
            "BARN OWL",
            "BARN SWALLOW",
            "BARRED OWL",
            "BARREN GROUND CARIBOU",
            "BARROW'S GOLDENEYE",
            "BAY-BREASTED WARBLER",
            "BEAVER",
            "BELTED KINGFISHER",
            "BENDIRE'S THRASHER",
            "BIG BROWN BAT",
            "BIGHORN SHEEP",
            "BLACK BEAR",
            "BLACK GUILLEMOT",
            "BLACK PHOEBE",
            "BLACK RAT",
            "BLACK SCOTER",
            "BLACK SWIFT",
            "BLACK TERN",
            "BLACK-AND-WHITE WARBLER",
            "BLACK-BACKED WOODPECKER",
            "BLACK-BELLIED PLOVER",
            "BLACK-BILLED CUCKOO",
            "BLACK-BILLED MAGPIE",
            "BLACK-CAPPED CHICKADEE",
            "BLACK-CHINNED HUMMINGBIRD",
            "BLACK-CROWNED NIGHT-HERON",
            "BLACK-FOOTED FERRET",
            "BLACK-HEADED GROSBEAK",
            "BLACK-LEGGED KITTIWAKE",
            "BLACK-NECKED STILT",
            "BLACK-THROATED BLUE WARBLER",
            "BLACK-THROATED GRAY WARBLER",
            "BLACK-THROATED GREEN WARBLER",
            "BLACK-THROATED SPARROW",
            "BLACKBURNIAN WARBLER",
            "BLACKPOLL WARBLER",
            "BLUE GROUSE",
            "BLUE JAY",
            "BLUE-GRAY GNATCATCHER",
            "BLUE-HEADED VIREO",
            "BLUE-WINGED TEAL",
            "BOBCAT",
            "BOBOLINK",
            "BOHEMIAN WAXWING",
            "BONAPARTE'S GULL",
            "BOREAL CHICKADEE",
            "BOREAL CHORUS FROG",
            "BOREAL OWL",
            "BOREAL TOAD",
            "BRAMBLING",
            "BRANT",
            "BREWER'S BLACKBIRD",
            "BREWER'S SPARROW",
            "BROAD-WINGED HAWK",
            "BROWN CREEPER",
            "BROWN LEMMING",
            "BROWN THRASHER",
            "BROWN-HEADED COWBIRD",
            "BUFF-BREASTED SANDPIPER",
            "BUFFLEHEAD",
            "BULL SNAKE",
            "BULLOCK'S ORIOLE",
            "BURROWING OWL",
            "BUSHY-TAILED WOODRAT",
            "CACKLING GOOSE",
            "CALIFORNIA GULL",
            "CALLIOPE HUMMINGBIRD",
            "CANADA GOOSE",
            "CANADA LYNX",
            "CANADA WARBLER",
            "CANADIAN TOAD",
            "CANVASBACK",
            "CANYON WREN",
            "CAPE MAY WARBLER",
            "CAROLINA WREN",
            "CASPIAN TERN",
            "CASSIN'S FINCH",
            "CASSIN'S SPARROW",
            "CASSIN'S VIREO",
            "CATTLE EGRET",
            "CEDAR WAXWING",
            "CHESTNUT-BACKED CHICKADEE",
            "CHESTNUT-COLLARED LONGSPUR",
            "CHESTNUT-SIDED WARBLER",
            "CHIMNEY SWIFT",
            "CHIPPING SPARROW",
            "CHUKAR",
            "CINNAMON TEAL",
            "CLARK'S GREBE",
            "CLARK'S NUTCRACKER",
            "CLASS AMPHIBIA",
            "CLASS AVES",
            "CLASS MAMMALIA",
            "CLASS REPTILIA",
            "CLAY-COLORED SPARROW",
            "CLIFF SWALLOW",
            "COLUMBIA SPOTTED FROG",
            "COLUMBIAN GROUND SQUIRREL",
            "COMMON CRANE",
            "COMMON GOLDENEYE",
            "COMMON GRACKLE",
            "COMMON LOON",
            "COMMON MERGANSER",
            "COMMON NIGHTHAWK",
            "COMMON POORWILL",
            "COMMON RAVEN",
            "COMMON REDPOLL",
            "COMMON SNIPE",
            "COMMON TERN",
            "COMMON YELLOWTHROAT",
            "CONNECTICUT WARBLER",
            "COOPER'S HAWK",
            "CORAL HAIRSTREAK",
            "CORDILLERAN FLYCATCHER",
            "COSTA'S HUMMINGBIRD",
            "COUGAR",
            "COYOTE",
            "CURLEW SANDPIPER",
            "DARK-EYED JUNCO",
            "DEER MOUSE",
            "DICKCISSEL",
            "DOMESTIC CHICKEN",
            "DOMESTIC COW",
            "DOMESTIC DOG",
            "DOMESTIC GOAT",
            "DOMESTIC PIG",
            "DOMESTIC SHEEP",
            "DONKEY",
            "DOUBLE-CRESTED CORMORANT",
            "DOWNY WOODPECKER",
            "DUNLIN",
            "DUSKY FLYCATCHER",
            "DUSKY SHREW",
            "EARED GREBE",
            "EASTERN BLUEBIRD",
            "EASTERN KINGBIRD",
            "EASTERN MEADOWLARK",
            "EASTERN PHOEBE",
            "EASTERN SCREECH-OWL",
            "EASTERN SHORT-HORNED LIZARD",
            "EASTERN TOWHEE",
            "EASTERN YELLOW-BELLIED RACER",
            "EMPEROR GOOSE",
            "ERMINE",
            "ESKIMO CURLEW",
            "EURASIAN COLLARED-DOVE",
            "EURASIAN WIGEON",
            "EUROPEAN STARLING",
            "EVENING GROSBEAK",
            "FALLOW DEER",
            "FAMILY ACCIPITRIDAE",
            "FAMILY ALAUDIDAE",
            "FAMILY ALCEDINIDAE",
            "FAMILY ALCIDAE",
            "FAMILY AMBYSTOMATIDAE",
            "FAMILY ANATIDAE",
            "FAMILY ANTILOCAPRIDAE",
            "FAMILY APODIDAE",
            "FAMILY ARDEIDAE",
            "FAMILY BOIDAE",
            "FAMILY BOMBYCILLIDAE",
            "FAMILY BOVIDAE",
            "FAMILY BUFONIDAE",
            "FAMILY CAMELIDAE",
            "FAMILY CANIDAE",
            "FAMILY CAPRIMULGIDAE",
            "FAMILY CARDINALIDAE",
            "FAMILY CASTORIDAE",
            "FAMILY CATHARTIDAE",
            "FAMILY CERTHIIDAE",
            "FAMILY CERVIDAE",
            "FAMILY CHARADRIIDAE",
            "FAMILY CHELYDRIDAE",
            "FAMILY CINCLIDAE",
            "FAMILY COLUBRIDAE",
            "FAMILY COLUMBIDAE",
            "FAMILY CORVIDAE",
            "FAMILY CUCULIDAE",
            "FAMILY DIPODIDAE",
            "FAMILY EMBERIZIDAE",
            "FAMILY EMYDIDAE",
            "FAMILY EQUIDAE",
            "FAMILY ERETHIZONTIDAE",
            "FAMILY FALCONIDAE",
            "FAMILY FELIDAE",
            "FAMILY FRINGILLIDAE",
            "FAMILY GAVIIDAE",
            "FAMILY GEOMYIDAE",
            "FAMILY GRUIDAE",
            "FAMILY HETEROMYIDAE",
            "FAMILY HIRUNDINIDAE",
            "FAMILY HYLIDAE",
            "FAMILY ICTERIDAE",
            "FAMILY IGUANIDAE",
            "FAMILY LANIIDAE",
            "FAMILY LARIDAE",
            "FAMILY LEPORIDAE",
            "FAMILY MEPHITIDAE",
            "FAMILY MIMIDAE",
            "FAMILY MOTACILLIDAE",
            "FAMILY MURIDAE",
            "FAMILY MUSTELIDAE",
            "FAMILY OCHOTONIDAE",
            "FAMILY ODONTOPHORIDAE",
            "FAMILY PARIDAE",
            "FAMILY PARULIDAE",
            "FAMILY PASSERIDAE",
            "FAMILY PELECANIDAE",
            "FAMILY PELOBATIDAE",
            "FAMILY PHALACROCORACIDAE",
            "FAMILY PHASIANIDAE",
            "FAMILY PICIDAE",
            "FAMILY PODICIPEDIDAE",
            "FAMILY PROCYONIDAE",
            "FAMILY RALLIDAE",
            "FAMILY RANIDAE",
            "FAMILY RECURVIROSTRIDAE",
            "FAMILY REGULIDAE",
            "FAMILY SCIURIDAE",
            "FAMILY SCOLOPACIDAE",
            "FAMILY SITTIDAE",
            "FAMILY SORICIDAE",
            "FAMILY STRIGIDAE",
            "FAMILY STURNIDAE",
            "FAMILY SUIDAE",
            "FAMILY SYLVIIDAE",
            "FAMILY THRAUPIDAE",
            "FAMILY THRESKIORNITHIDAE",
            "FAMILY TROCHILIDAE",
            "FAMILY TROGLODYTIDAE",
            "FAMILY TURDIDAE",
            "FAMILY TYRANNIDAE",
            "FAMILY TYTONIDAE",
            "FAMILY URSIDAE",
            "FAMILY VESPERTILIONIDAE",
            "FAMILY VIPERIDAE",
            "FAMILY VIREONIDAE",
            "FERAL PIG",
            "FERRUGINOUS HAWK",
            "FIELD SPARROW",
            "FISHER",
            "FLAMMULATED OWL",
            "FORK-TAILED FLYCATCHER",
            "FORSTER'S TERN",
            "FOX SPARROW",
            "FRANKLIN'S GROUND SQUIRREL",
            "FRANKLIN'S GULL",
            "FRINGED BAT",
            "FULVOUS WHISTLING DUCK",
            "GADWALL",
            "GARGANEY",
            "GENUS ACCIPITER",
            "GENUS ACTITIS",
            "GENUS AECHMOPHORUS",
            "GENUS AEGOLIUS",
            "GENUS AERONAUTES",
            "GENUS AGELAIUS",
            "GENUS AIMOPHILA",
            "GENUS AIX",
            "GENUS ALCES",
            "GENUS ALECTORIS",
            "GENUS ALOPEX",
            "GENUS AMBYSTOMA",
            "GENUS AMMODRAMUS",
            "GENUS AMPHISPIZA",
            "GENUS ANAS",
            "GENUS ANSER",
            "GENUS ANTHUS",
            "GENUS ANTILOCAPRA",
            "GENUS APHRIZA",
            "GENUS AQUILA",
            "GENUS ARCHILOCHUS",
            "GENUS ARDEA",
            "GENUS ARENARIA",
            "GENUS ASIO",
            "GENUS ATHENE",
            "GENUS AYTHYA",
            "GENUS BARTRAMIA",
            "GENUS BISON",
            "GENUS BOMBYCILLA",
            "GENUS BONASA",
            "GENUS BOS",
            "GENUS BOTAURUS",
            "GENUS BRANTA",
            "GENUS BUBO",
            "GENUS BUBULCUS",
            "GENUS BUCEPHALA",
            "GENUS BUFO",
            "GENUS BUTEO",
            "GENUS BUTORIDES",
            "GENUS CAIRINA",
            "GENUS CALAMOSPIZA",
            "GENUS CALCARIUS",
            "GENUS CALIDRIS",
            "GENUS CALYPTE",
            "GENUS CANIS",
            "GENUS CAPRA",
            "GENUS CAPRIMULGUS",
            "GENUS CARDINALIS",
            "GENUS CARDUELIS",
            "GENUS CARPODACUS",
            "GENUS CASTOR",
            "GENUS CATHARTES",
            "GENUS CATHARUS",
            "GENUS CATHERPES",
            "GENUS CATOPTROPHORUS",
            "GENUS CENTROCERCUS",
            "GENUS CEPPHUS",
            "GENUS CERTHIA",
            "GENUS CERVUS",
            "GENUS CERYLE",
            "GENUS CHAETURA",
            "GENUS CHARADRIUS",
            "GENUS CHARINA",
            "GENUS CHELYDRA",
            "GENUS CHEN",
            "GENUS CHLIDONIAS",
            "GENUS CHONDESTES",
            "GENUS CHORDEILES",
            "GENUS CHRYSEMYS",
            "GENUS CINCLUS",
            "GENUS CIRCUS",
            "GENUS CISTOTHORUS",
            "GENUS CLANGULA",
            "GENUS CLETHRIONOMYS",
            "GENUS COCCOTHRAUSTES",
            "GENUS COCCYZUS",
            "GENUS COLAPTES",
            "GENUS COLINUS",
            "GENUS COLUBER",
            "GENUS COLUMBA",
            "GENUS CONTOPUS",
            "GENUS CORVUS",
            "GENUS CORYNORHINUS",
            "GENUS COTURNICOPS",
            "GENUS CROTALUS",
            "GENUS CYANOCITTA",
            "GENUS CYGNUS",
            "GENUS CYPSELOIDES",
            "GENUS DAMA",
            "GENUS DENDRAGAPUS",
            "GENUS DENDROCYGNA",
            "GENUS DENDROICA",
            "GENUS DIPODOMYS",
            "GENUS DOLICHONYX",
            "GENUS DRYOCOPUS",
            "GENUS DUMETELLA",
            "GENUS ECTOPISTES",
            "GENUS EGRETTA",
            "GENUS ELANOIDES",
            "GENUS EMPIDONAX",
            "GENUS EPTESICUS",
            "GENUS EQUUS",
            "GENUS EREMOPHILA",
            "GENUS ERETHIZON",
            "GENUS EUPHAGUS",
            "GENUS EURYNORHYNCHUS",
            "GENUS FALCIPENNIS",
            "GENUS FALCO",
            "GENUS FELIS",
            "GENUS FRINGILLA",
            "GENUS FULICA",
            "GENUS GALLINAGO",
            "GENUS GAVIA",
            "GENUS GEOTHLYPIS",
            "GENUS GLAUCIDIUM",
            "GENUS GLAUCOMYS",
            "GENUS GRUS",
            "GENUS GULO",
            "GENUS GYMNORHINUS",
            "GENUS HALIAEETUS",
            "GENUS HETERODON",
            "GENUS HETEROSCELUS",
            "GENUS HIMANTOPUS",
            "GENUS HIRUNDO",
            "GENUS HISTRIONICUS",
            "GENUS HYLOCICHLA",
            "GENUS ICTERIA",
            "GENUS ICTERUS",
            "GENUS IXOREUS",
            "GENUS JUNCO",
            "GENUS LAGOPUS",
            "GENUS LAGURUS",
            "GENUS LAMA",
            "GENUS LANIUS",
            "GENUS LARUS",
            "GENUS LASIONYCTERIS",
            "GENUS LASIURUS",
            "GENUS LEMMISCUS",
            "GENUS LEMMUS",
            "GENUS LEPUS",
            "GENUS LEUCOSTICTE",
            "GENUS LIMNODROMUS",
            "GENUS LIMOSA",
            "GENUS LOPHODYTES",
            "GENUS LOXIA",
            "GENUS LUTRA",
            "GENUS LYNX",
            "GENUS MARMOTA",
            "GENUS MARTES",
            "GENUS MELANERPES",
            "GENUS MELANITTA",
            "GENUS MELEAGRIS",
            "GENUS MELOSPIZA",
            "GENUS MEPHITIS",
            "GENUS MERGUS",
            "GENUS MICROTUS",
            "GENUS MIMUS",
            "GENUS MNIOTILTA",
            "GENUS MOLOTHRUS",
            "GENUS MUS",
            "GENUS MUSTELA",
            "GENUS MYADESTES",
            "GENUS MYIARCHUS",
            "GENUS MYOTIS",
            "GENUS NEOTOMA",
            "GENUS NUCIFRAGA",
            "GENUS NUMENIUS",
            "GENUS NYCTEA",
            "GENUS NYCTICORAX",
            "GENUS OCHOTONA",
            "GENUS ODOCOILEUS",
            "GENUS OENANTHE",
            "GENUS ONDATRA",
            "GENUS ONYCHOMYS",
            "GENUS OPORORNIS",
            "GENUS OREAMNOS",
            "GENUS OREOSCOPTES",
            "GENUS OTUS",
            "GENUS OVIBOS",
            "GENUS OVIS",
            "GENUS OXYURA",
            "GENUS PAGOPHILA",
            "GENUS PANDION",
            "GENUS PARULA",
            "GENUS PASSER",
            "GENUS PASSERCULUS",
            "GENUS PASSERELLA",
            "GENUS PASSERINA",
            "GENUS PELECANUS",
            "GENUS PERDIX",
            "GENUS PERISOREUS",
            "GENUS PEROGNATHUS",
            "GENUS PEROMYSCUS",
            "GENUS PETROCHELIDON",
            "GENUS PHALACROCORAX",
            "GENUS PHALAENOPTILUS",
            "GENUS PHALAROPUS",
            "GENUS PHASIANUS",
            "GENUS PHENACOMYS",
            "GENUS PHEUCTICUS",
            "GENUS PHILOMACHUS",
            "GENUS PHRYNOSOMA",
            "GENUS PICA",
            "GENUS PICOIDES",
            "GENUS PINICOLA",
            "GENUS PIPILO",
            "GENUS PIRANGA",
            "GENUS PITUOPHIS",
            "GENUS PLECTROPHENAX",
            "GENUS PLEGADIS",
            "GENUS PLUVIALIS",
            "GENUS PODICEPS",
            "GENUS PODILYMBUS",
            "GENUS POECILE",
            "GENUS POLIOPTILA",
            "GENUS POOECETES",
            "GENUS PORZANA",
            "GENUS PROCYON",
            "GENUS PROGNE",
            "GENUS PSEUDACRIS",
            "GENUS QUISCALUS",
            "GENUS RALLUS",
            "GENUS RANA",
            "GENUS RANGIFER",
            "GENUS RATTUS",
            "GENUS RECURVIROSTRA",
            "GENUS REGULUS",
            "GENUS REITHRODONTOMYS",
            "GENUS RHODOSTETHIA",
            "GENUS RIPARIA",
            "GENUS RISSA",
            "GENUS SALPINCTES",
            "GENUS SAYORNIS",
            "GENUS SCIURUS",
            "GENUS SCOLOPAX",
            "GENUS SEIURUS",
            "GENUS SELASPHORUS",
            "GENUS SETOPHAGA",
            "GENUS SIALIA",
            "GENUS SITTA",
            "GENUS SOMATERIA",
            "GENUS SOREX",
            "GENUS SPEA",
            "GENUS SPERMOPHILUS",
            "GENUS SPHYRAPICUS",
            "GENUS SPIZA",
            "GENUS SPIZELLA",
            "GENUS STELGIDOPTERYX",
            "GENUS STELLULA",
            "GENUS STERCORARIUS",
            "GENUS STERNA",
            "GENUS STREPTOPELIA",
            "GENUS STRIX",
            "GENUS STURNELLA",
            "GENUS STURNUS",
            "GENUS SURNIA",
            "GENUS SUS",
            "GENUS SYLVILAGUS",
            "GENUS SYNAPTOMYS",
            "GENUS SYNTHLIBORAMPHUS",
            "GENUS TACHYCINETA",
            "GENUS TAMIAS",
            "GENUS TAMIASCIURUS",
            "GENUS TAXIDEA",
            "GENUS THAMNOPHIS",
            "GENUS THOMOMYS",
            "GENUS THRYOTHORUS",
            "GENUS TOXOSTOMA",
            "GENUS TRINGA",
            "GENUS TROGLODYTES",
            "GENUS TRYNGITES",
            "GENUS TURDUS",
            "GENUS TYMPANUCHUS",
            "GENUS TYRANNUS",
            "GENUS TYTO",
            "GENUS UROCYON",
            "GENUS URSUS",
            "GENUS VERMIVORA",
            "GENUS VIREO",
            "GENUS VULPES",
            "GENUS WILSONIA",
            "GENUS XANTHOCEPHALUS",
            "GENUS XEMA",
            "GENUS ZAPUS",
            "GENUS ZENAIDA",
            "GENUS ZONOTRICHIA",
            "GLAUCOUS GULL",
            "GLAUCOUS-WINGED GULL",
            "GOLDEN EAGLE",
            "GOLDEN-CROWNED KINGLET",
            "GOLDEN-CROWNED SPARROW",
            "GOLDEN-MANTLED GROUND SQUIRREL",
            "GOLDEN-WINGED WARBLER",
            "GRASSHOPPER SPARROW",
            "GRAY CATBIRD",
            "GRAY FOX",
            "GRAY JAY",
            "GRAY PARTRIDGE",
            "GRAY SQUIRREL",
            "GRAY WOLF",
            "GRAY-CHEEKED THRUSH",
            "GRAY-CROWNED ROSY-FINCH",
            "GREAT BLACK-BACKED GULL",
            "GREAT BLUE HERON",
            "GREAT CRESTED FLYCATCHER",
            "GREAT EGRET",
            "GREAT GRAY OWL",
            "GREAT HORNED OWL",
            "GREAT PLAINS TOAD",
            "GREATER PRAIRIE CHICKEN",
            "GREATER SAGE GROUSE",
            "GREATER SCAUP",
            "GREATER WHITE-FRONTED GOOSE",
            "GREATER YELLOWLEGS",
            "GREEN COMMA",
            "GREEN HERON",
            "GREEN-WINGED TEAL",
            "GRIZZLY BEAR",
            "GYRFALCON",
            "HAIRY WOODPECKER",
            "HAMMOND'S FLYCATCHER",
            "HARLEQUIN DUCK",
            "HARRIS'S SPARROW",
            "HEATHER VOLE",
            "HERMIT THRUSH",
            "HERRING GULL",
            "HOARY BAT",
            "HOARY MARMOT",
            "HOARY REDPOLL",
            "HOODED MERGANSER",
            "HOODED WARBLER",
            "HORNED GREBE",
            "HORNED LARK",
            "HORSE",
            "HOUSE FINCH",
            "HOUSE MOUSE",
            "HOUSE SPARROW",
            "HOUSE WREN",
            "HUDSONIAN GODWIT",
            "HUMAN",
            "ICELAND GULL",
            "INDIGO BUNTING",
            "IVORY GULL",
            "KENTUCKY WARBLER",
            "KILLDEER",
            "KING EIDER",
            "LAPLAND LONGSPUR",
            "LARK BUNTING",
            "LARK SPARROW",
            "LAZULI BUNTING",
            "LE CONTE'S SPARROW",
            "LEAST CHIPMUNK",
            "LEAST FLYCATCHER",
            "LEAST SANDPIPER",
            "LEAST WEASEL",
            "LESSER BLACK-BACKED GULL",
            "LESSER SCAUP",
            "LESSER YELLOWLEGS",
            "LEWIS'S WOODPECKER",
            "LINCOLN'S SPARROW",
            "LITTLE BLUE HERON",
            "LITTLE BROWN BAT",
            "LITTLE GULL",
            "LLAMA",
            "LOGGERHEAD SHRIKE",
            "LONG-BILLED CURLEW",
            "LONG-BILLED DOWITCHER",
            "LONG-EARED BAT",
            "LONG-EARED OWL",
            "LONG-LEGGED BAT",
            "LONG-TAILED DUCK",
            "LONG-TAILED JAEGER",
            "LONG-TAILED VOLE",
            "LONG-TAILED WEASEL",
            "LONG-TOED SALAMANDER",
            "MACGILLIVRAY'S WARBLER",
            "MAGNOLIA WARBLER",
            "MALLARD",
            "MARBLED GODWIT",
            "MARSH WREN",
            "MARTEN",
            "MASKED SHREW",
            "MCCOWN'S LONGSPUR",
            "MEADOW JUMPING MOUSE",
            "MEADOW VOLE",
            "MERLIN",
            "MEW GULL",
            "MINK",
            "MONGOLIAN PLOVER",
            "MOOSE",
            "MOUNTAIN BLUEBIRD",
            "MOUNTAIN CHICKADEE",
            "MOUNTAIN GOAT",
            "MOUNTAIN PLOVER",
            "MOURNING DOVE",
            "MOURNING WARBLER",
            "MULE DEER",
            "MUSCOVY DUCK",
            "MUSKOX",
            "MUSKRAT",
            "NASHVILLE WARBLER",
            "NELSON'S SHARP-TAILED SPARROW",
            "NONE",
            "NORTHERN BOBWHITE",
            "NORTHERN BOG LEMMING",
            "NORTHERN CARDINAL",
            "NORTHERN CRESCENT",
            "NORTHERN FLICKER",
            "NORTHERN FLYING SQUIRREL",
            "NORTHERN GOSHAWK",
            "NORTHERN GRASSHOPPER MOUSE",
            "NORTHERN HARRIER",
            "NORTHERN HAWK OWL",
            "NORTHERN LEOPARD FROG",
            "NORTHERN LONG-EARED BAT",
            "NORTHERN MOCKINGBIRD",
            "NORTHERN PARULA",
            "NORTHERN PINTAIL",
            "NORTHERN POCKET GOPHER",
            "NORTHERN PYGMY-OWL",
            "NORTHERN ROUGH-WINGED SWALLOW",
            "NORTHERN SAW-WHET OWL",
            "NORTHERN SHOVELER",
            "NORTHERN SHRIKE",
            "NORTHERN WATERTHRUSH",
            "NORTHERN WHEATEAR",
            "NORWAY RAT",
            "NUTTALL'S COTTONTAIL",
            "OLIVE-BACKED POCKET MOUSE",
            "OLIVE-SIDED FLYCATCHER",
            "ORANGE-CROWNED WARBLER",
            "ORD'S KANGAROO RAT",
            "ORDER ANSERIFORMES",
            "ORDER ANURA",
            "ORDER APODIFORMES",
            "ORDER ARTIODACTYLA",
            "ORDER CAPRIMULGIFORMES",
            "ORDER CARNIVORA",
            "ORDER CAUDATA",
            "ORDER CHARADRIIFORMES",
            "ORDER CHIROPTERA",
            "ORDER CICONIIFORMES",
            "ORDER COLUMBIFORMES",
            "ORDER CORACIIFORMES",
            "ORDER CUCULIFORMES",
            "ORDER FALCONIFORMES",
            "ORDER GALLIFORMES",
            "ORDER GAVIIFORMES",
            "ORDER GRUIFORMES",
            "ORDER INSECTIVORA",
            "ORDER LAGOMORPHA",
            "ORDER PASSERIFORMES",
            "ORDER PELECANIFORMES",
            "ORDER PERISSODACTYLA",
            "ORDER PICIFORMES",
            "ORDER PODICIPEDIFORMES",
            "ORDER RODENTIA",
            "ORDER SQUAMATA",
            "ORDER STRIGIFORMES",
            "ORDER TESTUDINATA",
            "OSPREY",
            "OVENBIRD",
            "PACIFIC LOON",
            "PACIFIC WREN",
            "PACIFIC-SLOPE FLYCATCHER",
            "PALM WARBLER",
            "PARASITIC JAEGER",
            "PASSENGER PIGEON",
            "PECTORAL SANDPIPER",
            "PEREGRINE FALCON",
            "PHILADELPHIA VIREO",
            "PIED-BILLED GREBE",
            "PIKA",
            "PILEATED WOODPECKER",
            "PINE GROSBEAK",
            "PINE SISKIN",
            "PINE WARBLER",
            "PINK-EDGED SULPHUR",
            "PINYON JAY",
            "PIPING PLOVER",
            "PLAINS GARTER SNAKE",
            "PLAINS SPADEFOOT",
            "POMARINE JAEGER",
            "PORCUPINE",
            "PRAIRIE FALCON",
            "PRAIRIE RATTLESNAKE",
            "PRAIRIE SHREW",
            "PRAIRIE VOLE",
            "PRONGHORN",
            "PURPLE FINCH",
            "PURPLE MARTIN",
            "PYGMY NUTHATCH",
            "PYGMY SHREW",
            "RACCOON",
            "RED BAT",
            "RED CROSSBILL",
            "RED FOX",
            "RED KNOT",
            "RED PHALAROPE",
            "RED SQUIRREL",
            "RED-BREASTED MERGANSER",
            "RED-BREASTED NUTHATCH",
            "RED-BREASTED SAPSUCKER",
            "RED-EYED VIREO",
            "RED-HEADED WOODPECKER",
            "RED-NAPED SAPSUCKER",
            "RED-NECKED GREBE",
            "RED-NECKED PHALAROPE",
            "RED-NECKED STINT",
            "RED-SHOULDERED HAWK",
            "RED-SIDED GARTER SNAKE",
            "RED-TAILED CHIPMUNK",
            "RED-TAILED HAWK",
            "RED-THROATED LOON",
            "RED-WINGED BLACKBIRD",
            "REDHEAD",
            "RICHARDSON'S GROUND SQUIRREL",
            "RING-BILLED GULL",
            "RING-NECKED DUCK",
            "RING-NECKED PHEASANT",
            "RIVER OTTER",
            "ROCK DOVE",
            "ROCK PTARMIGAN",
            "ROCK WREN",
            "ROSE-BREASTED GROSBEAK",
            "ROSS'S GOOSE",
            "ROSS'S GULL",
            "ROUGH-LEGGED HAWK",
            "RUBBER BOA",
            "RUBY-CROWNED KINGLET",
            "RUBY-THROATED HUMMINGBIRD",
            "RUDDY DUCK",
            "RUDDY TURNSTONE",
            "RUFF",
            "RUFFED GROUSE",
            "RUFOUS HUMMINGBIRD",
            "RUSTIC BLUE",
            "RUSTY BLACKBIRD",
            "SABINE'S GULL",
            "SAGE THRASHER",
            "SAGEBRUSH VOLE",
            "SANDERLING",
            "SANDHILL CRANE",
            "SAVANNAH SPARROW",
            "SAY'S PHOEBE",
            "SCARLET TANAGER",
            "SCISSOR-TAILED FLYCATCHER",
            "SEDGE WREN",
            "SEMIPALMATED PLOVER",
            "SEMIPALMATED SANDPIPER",
            "SHARP-SHINNED HAWK",
            "SHARP-TAILED GROUSE",
            "SHARP-TAILED SANDPIPER",
            "SHORT-BILLED DOWITCHER",
            "SHORT-EARED OWL",
            "SILVER-HAIRED BAT",
            "SMITH'S LONGSPUR",
            "SNAPPING TURTLE",
            "SNOW BUNTING",
            "SNOW GOOSE",
            "SNOWSHOE HARE",
            "SNOWY EGRET",
            "SNOWY OWL",
            "SNOWY PLOVER",
            "SOLITARY SANDPIPER",
            "SONG SPARROW",
            "SORA",
            "SOUTHERN RED-BACKED VOLE",
            "SPOONBILL SANDPIPER",
            "SPOTTED REDSHANK",
            "SPOTTED SANDPIPER",
            "SPOTTED TOWHEE",
            "SPRAGUE'S PIPIT",
            "SPRUCE GROUSE",
            "STELLER'S JAY",
            "STILT SANDPIPER",
            "STRIPED HAIRSTREAK",
            "STRIPED SKUNK",
            "SURF SCOTER",
            "SURFBIRD",
            "SWAINSON'S HAWK",
            "SWAINSON'S THRUSH",
            "SWAMP SPARROW",
            "SWIFT FOX",
            "TAIGA (YELLOW-CHEEKED) VOLE",
            "TAWNY CRESCENT",
            "TENNESSEE WARBLER",
            "THAYER'S GULL",
            "THIRTEEN-LINED GROUND SQUIRREL",
            "THREE-TOED WOODPECKER",
            "TIGER SALAMANDER",
            "TOWNSEND'S LONG-EARED BAT",
            "TOWNSEND'S SOLITAIRE",
            "TOWNSEND'S WARBLER",
            "TRAILL'S FLYCATCHER",
            "TREE SWALLOW",
            "TRICOLORED HERON",
            "TRUMPETER SWAN",
            "TUFTED DUCK",
            "TUNDRA SWAN",
            "TURKEY VULTURE",
            "UPLAND SANDPIPER",
            "VAGRANT SHREW / WANDERING SHREW",
            "VARIED THRUSH",
            "VAUX'S SWIFT",
            "VEERY",
            "VESPER SPARROW",
            "VIOLET-GREEN SWALLOW",
            "VIRGINIA RAIL",
            "VIRGINIA'S WARBLER",
            "WANDERING GARTER SNAKE",
            "WANDERING SHREW",
            "WANDERING TATTLER",
            "WAPITI",
            "WARBLING VIREO",
            "WATER SHREW",
            "WATER VOLE",
            "WESTERN BLUEBIRD",
            "WESTERN GREBE",
            "WESTERN HARVEST MOUSE",
            "WESTERN HOG-NOSED SNAKE",
            "WESTERN JUMPING MOUSE",
            "WESTERN KINGBIRD",
            "WESTERN MEADOWLARK",
            "WESTERN PAINTED TURTLE",
            "WESTERN SANDPIPER",
            "WESTERN SCREECH-OWL",
            "WESTERN SMALL-FOOTED BAT",
            "WESTERN TANAGER",
            "WESTERN WOOD-PEWEE",
            "WHIMBREL",
            "WHIP-POOR-WILL",
            "WHITE-BREASTED NUTHATCH",
            "WHITE-CROWNED SPARROW",
            "WHITE-FACED IBIS",
            "WHITE-HEADED WOODPECKER",
            "WHITE-RUMPED SANDPIPER",
            "WHITE-TAILED DEER",
            "WHITE-TAILED DEER X MULE DEER HYBRID",
            "WHITE-TAILED JACK RABBIT",
            "WHITE-TAILED PTARMIGAN",
            "WHITE-THROATED SPARROW",
            "WHITE-THROATED SWIFT",
            "WHITE-WINGED CROSSBILL",
            "WHITE-WINGED SCOTER",
            "WHOOPING CRANE",
            "WILD TURKEY",
            "WILLET",
            "WILLIAMSON'S SAPSUCKER",
            "WILLOW FLYCATCHER",
            "WILLOW PTARMIGAN",
            "WILSON'S PHALAROPE",
            "WILSON'S SNIPE",
            "WILSON'S SNIPE",
            "WILSON'S WARBLER",
            "WINTER WREN",
            "WOLVERINE",
            "WOOD DUCK",
            "WOOD FROG",
            "WOOD THRUSH",
            "WOODCHUCK",
            "WOODLAND CARIBOU",
            "YELLOW RAIL",
            "YELLOW WARBLER",
            "YELLOW-BELLIED FLYCATCHER",
            "YELLOW-BELLIED MARMOT",
            "YELLOW-BELLIED SAPSUCKER",
            "YELLOW-BILLED CUCKOO",
            "YELLOW-BILLED LOON",
            "YELLOW-BILLED MAGPIE",
            "YELLOW-BREASTED CHAT",
            "YELLOW-HEADED BLACKBIRD",
            "YELLOW-PINE CHIPMUNK",
            "YELLOW-RUMPED WARBLER",
            "YELLOW-THROATED VIREO"
        ];
        #endregion

        #region Alberta Standard: Folder Metadata as a Row List
        public static List<StandardsRow> FolderMetadataRows =
        [
            #region Level 1: Project
            new(
                Control.AlphaNumeric, 1, "", "Project Name", "proj_name",
                $"A unique alphanumeric identifier for each project.{Environment.NewLine}" +
                "• e.g., \"uofa_oilsands_2018\"",
                null),

            new(Control.Note, 1, "", "Project Coordinator", "proj_coord",
                $"The first and last name of the primary contact.{Environment.NewLine}" +
                " • e.g., \"John Smith\"",
                null),

            new(Control.Note, 1, "", "Project Coordinator Email", "proj_coord_email",
                $"The email address of the Project Coordinator.{Environment.NewLine}" +
                " • e.g., \"John.Smith@telus.net\"",
                null),

            new(Control.MultiLine, 1, "", "Project Description", "proj_desc",
                $"A description of the project objective(s) and general methods.{Environment.NewLine}" +
                "• e.g., \"To compare wolf occupancy in the oil sands region of north-eastern Alberta in two areas with high energy development and two reference areas with little development.\"",
                null),
            #endregion

            #region Level 2: Study Area
            new(Control.AlphaNumeric, 2, "", "Study Area Name", "study_area_name",
                $"A unique alphanumeric identifier for each study area.{Environment.NewLine}" +
                "• e.g.,\"oilsands_ref1\"",
                null),

            new(Control.MultiLine, 2, "", "Study Area Description", "study_area_desc",
                $"A description for each unique research or monitoring area including its location, the habitat type(s), land use(s) and habitat disturbances (where applicable).{Environment.NewLine}" +
                "• e.g.,\"Located in the SE corner of Birch Mountains Wildland Provincial Park in Boreal Highlands subregion.  Bogs, pine, aspen and birch forest. No land use disturbance.\"",
                null),
            #endregion

            #region Level 3: Survey
            new(Control.AlphaNumeric, 3, "", "Survey Name", "surv_name",
                $"A unique alphanumeric identifier for each survey period.{Environment.NewLine}" +
                "• e.g., \"fortmc_1\"",
                null),

            new(Control.MultiLine, 3, "", "Survey Objectives", "surv_obj",
                $"The specific objectives of each survey within a project, including the Target Species, the state variables (e.g., occupancy, density) , and proposed modelling approach(es).{Environment.NewLine}" +
                "• e.g., \"To monitor trends in wolf occupancy at 5-year intervals from January – December 2020 to 2023.\"",
                null),

            new(Control.MultiChoice, 3, "", "Target Species", "target_species",
                $"The common name(s) of the species being categorized (tagged).{Environment.NewLine}" +
                "• e.g., \"gray wolf\"",
                StandardsBase.CreateChoiceList(true, SpeciesCommonList)),

            new(Control.FixedChoice, 3, "", "Survey Design", "surv_design",
                $"The spatial arrangement of remote cameras within the study area for an individual survey.{Environment.NewLine}" +
                $"If “Hierarchical (multiple)*”, include additional details in the Survey Design Description.{Environment.NewLine}" +
                "• e.g., \"Hierarchical (multiple)\"",
                StandardsBase.CreateChoiceList(true,
                    ["Simple Random", "Systematic", "Stratified", "Clustered", "Paired", "Targeted", "Convenience", "Hierarchical (Multiple)", "Other", "Unknown"])),

            new(Control.MultiLine, 3, "", "*Survey Design Description", "surv_design_desc",
                $"Any additional details about the Survey Design.{Environment.NewLine}" +
                "• e.g., \"Survey_Design[Systematic, Convenience]. One camera location within each township. Each location within 100m of a secondary road or cutline. Lure dispensers with Gorman’s Gumbo (long line) at each camera location during initial camera deployment and not revisited during the survey period.\"",
                null),
            
            new(Control.FixedChoice, 3, "", "Event Type", "event_type",
                $"Whether detections were reported as an individual image captured by the camera (\"Image\"), a \"Sequence,\", or \"Tag\".{Environment.NewLine}" +
                "• e.g., \"Tag\"",
                StandardsBase.CreateChoiceList(true, ["Tag", "Image", "Sequence"])),
            #endregion

            #region Level 4: Sample Station

            // Alphanumeric
            new(Control.AlphaNumeric, 4, "", "Camera Location Name", "cam_loc_name",
                $"A unique alphanumeric identifier for the location where a single camera was placed.{Environment.NewLine}" +
                "• e.g., \"bh1\"",
                null),

            new(Control.AlphaNumeric, 4, "", "Sample Station Name", "samp_st_name",
                $"An alphanumeric identifier for each grouping of two more non-independent camera locations (when cameras are deployed in clusters, pairs, or arrays, e.g., “ss1” in “ss1_bh1”, “ss1_bh2”, “ss1_bh3” etc.).{Environment.NewLine}" +
                $"• Leave blank if not applicable{Environment.NewLine}" +
                "• e.g., \"ss1\"",
                null),

            new(Control.DecimalAny, 4, "", "Latitude Camera Location", "cam_loc_lat",
                $"The latitude of the camera location in decimal degrees to five decimal places.{Environment.NewLine}" +
                $"Leave blank if recording the Northing instead.{Environment.NewLine}" +
                "• e.g., \"53.78136\"",
                null),

            new(Control.DecimalAny, 4, "", "Longitude Camera Location", "cam_loc_long",
                $"The longitude of the camera location in decimal degrees to five decimal places.{Environment.NewLine}" +
                $"Leave blank if recording the Easting instead.{Environment.NewLine}" +
                "• e.g., \"-113.46067\"",
                null),

            new(Control.IntegerPositive, 4, "", "Northing Camera Location", "cam_loc_north",
                $"The northing UTM coordinate of the camera location. Record using the NAD83 datum.{Environment.NewLine}" +
                $"Leave blank if recording the Latitude instead.{Environment.NewLine}" +
                "• e.g., \"5962006\"",
                null),

            new(Control.IntegerPositive, 4, "", "Easting Camera Location", "cam_loc_east",
                $"The easting  UTM coordinate of the camera location using NAD83 datum.{Environment.NewLine}" +
                $"Leave blank if recording the Longitude instead.{Environment.NewLine}" +
                "• e.g., \"337875\"",
                null),

            new(Control.IntegerPositive, 4, "", "UTM Zone Camera Location", "cam_loc_utm_zone",
            $"The coordinate system that divides geographic areas into north-south zones.{Environment.NewLine}" +
                $"Enter all other UTM zones in the Camera Location Comments field (e.g., zones 7-10 for British Columbia), or use Latitude and Longitude instead of UTM coordinates.{Environment.NewLine}" +
                "• e.g., \"12\"",
                StandardsBase.CreateChoiceList(true, ["11", "12", "TTM"])),

            new(Control.IntegerPositive, 4, "", "GPS Unit Accuracy (m)", "gps_accuracy_m",
                $"The margin of error of the GPS unit used to record spatial information in meters, such as the coordinates of the camera location.{Environment.NewLine}" +
                "• e.g., \"5\"",
                null),

            new(Control.MultiLine, 4, "", "* Camera Location Comments", "cam_loc_comments",
                $"Any additional details about a camera location{Environment.NewLine}" +
                "• e.g., \"Snowmobile trail\"",
                null),
            #endregion

            #region Level 5: Deployment
            new(Control.AlphaNumeric, 5, "", "Deployment Name", "deploy_name",
                $"A unique alphanumeric identifier for a unique camera deployed during a specific survey period.{Environment.NewLine}" +
                $"Ideally recorded as: \"Camera Location ID\"_\"Deployment Start Date_\" (or ..._\"Deployment End Date_\"){Environment.NewLine}" +
                $"Alternative naming conventions may be used.{Environment.NewLine}" +
                "• e.g., \"bh1_17-Jan-2018\"",
                null),

            new(Control.MultiLine, 5, "", "Deployment Crew", "deploy_crew",
                $"The first and last names of all the individuals who collected data during deployment visit.{Environment.NewLine}" +
                "• e.g., \"Suzie Smith\"",
                null),

            new(Control.MultiLine, 5, "", "Service/Retrieval Crew", "service_retrieval_crew",
                $"The first and last names of all the individuals who collected data during the service/retrieval visit.{Environment.NewLine}" +
                "• e.g., \"John Smith\"",
                null),


            new(Control.DateTime_, 5, 
                Timelapse.Util.DateTimeHandler.ToStringDatabaseDateTime(Timelapse.Constant.ControlDefault.DateTimeCustomDefaultValue),
                "Deployment Start Date_ Time_", "deploy_start_date_time",
                $"The date and time that a camera was placed for a specific deployment.{Environment.NewLine}" +
                "• e.g., \"17-Jan-2018 10:34:22\"",
                null),

            new(Control.DateTime_, 5,
                Timelapse.Util.DateTimeHandler.ToStringDatabaseDateTime(Timelapse.Constant.ControlDefault.DateTimeCustomDefaultValue), "Deployment End Date_ Time_", "deploy_end_date_time",
                $"The date and time that the data was retrieved for a specific deployment.{Environment.NewLine}" +
                "• e.g., \"27-Jan-2019 23:00:00\"",
                null),

            new(Control.MultiLine, 5, "", "* Visit Comments", "visit_comments",
                $"Any additional details about the deployment and/or service/retrieval visits.{Environment.NewLine}" +
                "• e.g., \"Remaining Battery (%)\"",
                null),
           
            new(Control.AlphaNumeric, 5, "", "Camera ID", "cam_id",
                $"A unique alphanumeric ID for the camera that distinguishes it from other cameras of the same make or model.{Environment.NewLine}" +
                "• e.g., \"reconpc900-1\"",
                null),

            new(Control.Note, 5, "", "Camera Make", "cam_make",
                $"The make of a particular camera.{Environment.NewLine}" +
                "• e.g., \"Reconyx\"", null),

            new(Control.Note, 5, "", "Camera Model", "cam_model",
                $"The model number or name of a particular camera.{Environment.NewLine}" +
                "• e.g., \"PC900\"",
                null),

            new(Control.Note, 5, "", "Camera Serial Number", "cam_serial",
                $"The serial number of a particular camera..{Environment.NewLine}" +
                "• e.g., \"P900FF04152022\"",
                null),

            new(Control.FixedChoice, 5, "", "Trigger Mode(s)", "set_trig_modes",
                $"The camera setting(s) that determine how the camera will trigger:{Environment.NewLine}" +
                $"by motion (Motion Image), at set intervals (Time_-lapse image), and/or by video (Video).{Environment.NewLine}" +
                "• e.g., \"Motion Image + Time_-lapse Image\"",
                StandardsBase.CreateChoiceList(true,
                [
                    "Motion Image", "Time_-lapse Image", "Video", "Motion Image + Time_-lapse Image", "Motion Image + Time_-lapse Image + Video", "Time_-lapse Image + Video",
                    "Motion Image + Video"
                ])),
            
            new(Control.IntegerPositive, 5, "", "* Video Length (seconds)", "set_video_length_s",
                $"If applicable, the camera setting that specifies the minimum video duration (in seconds) that the camera will record when triggered.{Environment.NewLine}" +
                $"• Leave blank if not applicable.{Environment.NewLine}" +
                "• e.g., \"0\"",
                null),

            new(Control.FixedChoice, 5, "", "Trigger Sensitivity", "set_trig_sensitivity",
                $"The camera setting responsible for how sensitive a camera is to activation (to \"triggering\") via the infrared and/or heat detectors.{Environment.NewLine}" +
                "• e.g., \"High\"",
                StandardsBase.CreateChoiceList(true, ["Low", "Low/Med", "Med", "Med/High", "High", "Very High", "Unknown"])),

            new(Control.IntegerPositive, 5, "", "Photos Per Trigger", "set_photos_per_trig",
                $"The setting that describes the number of photos taken each time the camera is triggered.{Environment.NewLine}" +
                "• e.g., \"3\"",
                null),

            new(Control.IntegerPositive, 5, "0", "Motion Image Interval (seconds)", "set_motion_img_int_s",
                $"The time (in seconds) between images within a multi-image sequence that occur due to motion, heat, or activation of external detector devices.{Environment.NewLine}" +
                $"If not set, enter \"0\" seconds (i.e., instantaneous){Environment.NewLine}" +
                "• e.g., \"0\"",
                null),

            new(Control.IntegerPositive, 5, "0", "Quiet Period (seconds)", "set_quiet_period_s",
                $"The user-defined camera setting which provides the time (in seconds) between shutter \"triggers\" if the camera was programmed to pause between firing initially and firing a second time. {Environment.NewLine}" +
                $"If not set, enter \"0.\"{Environment.NewLine}" +
                "• e.g., \"30\"",
                null),

            new(Control.DecimalPositive, 5, "0", "Camera Height (m)", "cam_ht_m",
                $"The height from the ground (below snow) to the bottom of the lens (metres; to the nearest 0.05 m).{Environment.NewLine}" +
                "• e.g., \"1.05\"",
                null),

            new(Control.IntegerPositive, 5, "0", "* Camera Direction (degrees)", "cam_dir_deg",
                $"The cardinal direction that a camera faces (in degrees). Ideally, cameras should face north, or south if north is not possible.{Environment.NewLine}" +
                "• e.g., \"0\")",
                null),

            new(Control.DecimalPositive, 5, "", "* Stake Distance (m)", "stake_dist_m",
                $"The distance from the camera to a stake (metres; to the nearest 0.05 m). {Environment.NewLine}" +
                $"• Leave blank if not applicable.{Environment.NewLine}" +
                "• e.g., \"4.95\"",
                null),

            new(Control.FixedChoice, 5, "", "FOV Target Feature", "fov_target",
                $"A specific man-made or natural feature at which the camera is aimed to maximize the detection of wildlife species or to measure the use of that feature.{Environment.NewLine}" +
                $"Record \"None\" if a FOV Target Feature was not used and \"Unknown\" if not known. {Environment.NewLine}" +
                $"If \"Other,\" describe in the Camera Location Comments.{Environment.NewLine}" +
                "• e.g., \"Off-Highway Vehicle Trail\"",
                StandardsBase.CreateChoiceList(false, [
                    "Game Trail", "Hiking Trail", "Off-Highway Vehicle Trail", "Paved Road", "Dirt/Gravel Road", "Road Crossing", "Railway", "Cutline/Seismic Line",
                    "Transmission Line", "Pipeline", "Wellsite", "Culvert", "Beaver Dam", "Burrow/Den", "Nest", "Carcass", "Natural Mineral Lick", "Rub Post", "Other", "None",
                    "Unknown"
                ])),

            new(Control.DecimalPositive, 5, "0", "* FOV Target Feature Distance (m)", "fov_target_dist_m",
                $"The distance from the camera to the FOV Target Feature (metres; to the nearest 0.5 m).{Environment.NewLine}" +
                $"• Leave blank if not applicable.{Environment.NewLine}" +
                "• e.g., \"10\"",
                null),

            new(Control.FixedChoice, 5, "", "Bait/Lure Type", "bait_lure_type",
                $"The type of bait or lure used at a camera location.{Environment.NewLine}" +
                $"Record \"None\" if bait/lure was not used and \"Unknown\" if not known.{Environment.NewLine}" + 
                $"If \"Other,\" describe in the Deployment Comments.{Environment.NewLine}" +
                "• e.g., \"Scent\"",
                StandardsBase.CreateChoiceList(false, ["Scent", "Meal", "Bait Tree", "Visual", "Acoustic", "Other", "None", "Unknown"])),

            new(Control.MultiChoice, 5, "", "* Camera Location Characteristic(s)", "cam_loc_chars",
                $"Any significant features around the camera at the time of the visit (including those not in the camera's Field of View). {Environment.NewLine}" +
                $"If \"Other,\" describe in the Camera Location Comments.{Environment.NewLine}" +
                "• e.g., \"Building, Forest - Mixedwood, Road, Trail\"",
                StandardsBase.CreateChoiceList(false, [
                    "Trail", "Road", "Railway/Pipeline/Transmission Line", "Cutline/Seismic Line", "Wellsite", "Clearcut", "Building", " Forest - Deciduous", "Forest - Coniferous",
                    "Forest - Mixedwood", "Forest - Undefined", "Meadow", "Burn", "Agriculture", "Shrubland", "Beaver Dam", "Wetland", "Lentic", "Lotic", "Other", "Unknown"
                ])),

            new(Control.DecimalPositive, 5, "0", "* Walktest Distance (m)", "walktest_dist_m",
                $"The horizontal distance from the camera at which the crew performs the walktest (metres; to the nearest 0.05 m).{Environment.NewLine}" +
                $"Leave blank if not applicable.{Environment.NewLine}" +
                 "• e.g., \"4.95\"",
                null),

            new(Control.DecimalPositive, 5, "0", "* Walktest Height (m)", "walktest_ht_m",
                $"The vertical distance from the camera at which the crew performs the walktest (metres; to the nearest 0.05 m).{Environment.NewLine}" +
                $"Leave blank if not applicable.{Environment.NewLine}" +
                 "• e.g., \"0.75\"",
                null),

            new(Control.DateTime_, 5,
                Timelapse.Util.DateTimeHandler.ToStringDatabaseDateTime(Timelapse.Constant.ControlDefault.DateTimeCustomDefaultValue), 
                "Image Set Start Date_ Time_", "img_set_start_date_time",
                $"The date and time of the first image or video collected during a specific deployment.{Environment.NewLine}" +
                "• e.g., \"17-Jan-2018 12:00:02\"",
                null),

            new(Control.DateTime_, 5, 
                Timelapse.Util.DateTimeHandler.ToStringDatabaseDateTime(Timelapse.Constant.ControlDefault.DateTimeCustomDefaultValue),
                "Image Set End Date_ Time_", "img_set_end_date_time",
                $"The date and time of the last image or video collected during a specific deployment.{Environment.NewLine}" +
                "• e.g., \"17-Jan-2019 22:10:05\r\n\"",
                null),

            new(Control.IntegerPositive, 5, "", "* Deployment Image Count", "deploy_img_count",
                $"The total number of images collected during the deployment, including false triggers (i.e., empty images) and time-lapse images (if applicable).{Environment.NewLine}" +
                "• e.g., \"1567\"",
                null),
        ];
        #endregion

        #endregion

        #region Alberta Standard: Image template as a Row List

        public static List<StandardsRow> ImageTemplateRows =
        [
            new(
                Control.AlphaNumeric, 1, "", "Image Name", "img_id",
                $"A unique alphanumeric identifier for the image.{Environment.NewLine}" +
                "• e.g., \"\"bh1_17-Jul-2018_22-Jul-2018_10:34:22_img_100\"",
                null, copyable: false),

            // Alphanumeric

            new(
                Control.AlphaNumeric, 1, "", "Sequence Name", "seq_id",
                $"A unique alphanumeric identifier for a multi-image sequence.{Environment.NewLine}" +
                "e.g., \"bh1_22-Jul-2018_img_001-img_005\r\n\"",
                null),



            new(
                Control.Note, 1, "", "Analyst", "analyst",
                $"The first and last names of the individual who provided the observation data point (species identification and associated information).{Environment.NewLine}" +
                $"If there are multiple Analysts for an observation, enter the primary Analyst.{Environment.NewLine}" +
                "e.g., \"Susie Smith\"",
                null),


            new(
                Control.FixedChoice, 1, "", "Species", "species",
                $"The common name of the species being categorized (\"tagged\"). {Environment.NewLine}" +
                $"Refine the list by typing in the first few letters of the species common name.{Environment.NewLine}" +
                "e.g., \"coyote\"",
                StandardsBase.CreateChoiceList(true, SpeciesCommonList)),


            new(
                Control.IntegerPositive, 1, "", "Individual Count", "individual_count",
                $"The number of unique individuals being categorized.{Environment.NewLine}" +
                "e.g., \"2\"",
                null),


            new(
                Control.FixedChoice, 1, "", "Age Class", "age_class",
                $"The age classification of individual(s) being categorized.{Environment.NewLine}" +
                "e.g., \"Adult\"",
                StandardsBase.CreateChoiceList(true, ["Adult", "Juvenile", "Subadult", "Subadult - Young of Year", "Subadult - Yearling", "Unknown"])),


            new(
                Control.FixedChoice, 1, "", "Sex Class", "sex_class",
                $"The sex classification of individual(s) being categorized.{Environment.NewLine}" +
                "e.g., \"Male\"",
                StandardsBase.CreateChoiceList(true, ["Male", "Female", "Unknown"])),


            new(
                Control.FixedChoice, 1, "", "*Behaviour", "behaviour",
                $"The behaviour of individual(s) being categorized.{Environment.NewLine}" +
                "e.g., \"Travelling\"",
                StandardsBase.CreateChoiceList(true, [
                    "Travelling", "Standing", "Running", "Standing", "Bedding", "Drinking", "Feeding/Foraging", "Territorial Display",
                    "Rutting/Mating", "Vigilant", "Inspecting Camera", "Inspecting (Non-specified)", "Other", "Multiple", "Unknown"
                ])),

            // Alphanumeric

            new(
                Control.AlphaNumeric, 1, "", "*Animal ID", "animal_id",
                $"A unique identifier for an animal that can be uniquely identified (e.g., marked in some way). {Environment.NewLine}" +
                $"If multiple unique individuals are identified, enter an Animal ID for each as a unique row{Environment.NewLine}" +
                "e.g., \"individual_1\"",
                null),


            new(
                Control.FixedChoice, 1, "", "*Human Transport Mode/Activity", "human_tpt_mode_activity",
                $"The activity performed or mode of transportation used by a human observed.{Environment.NewLine}" +
                $" Leave blank if not applicable and record \"Unknown\" if not known{Environment.NewLine}" +
                "e.g., \"Activity - Walking\"",
                StandardsBase.CreateChoiceList(true, [
                    "Activity - Walking", "Activity - Hiking", "Activity - Running", "Activity - Cycling", "Activity - Skiing", "Activity - Snowshoeing", "Activity- Fishing",
                    "Activity - Hunting",
                    "Activity - Unspecified", "Transport - Horse/Mule", "Transport - Off-Highway Vehicle", "Transport - Passenger Vehicle",
                    "Transport - Large Commercial Vehicle/Heavy Equipment",
                    "Transport - Unspecified", "Other", "Activity/Transport - Other"
                ])),


            new(
                Control.Note, 1, "", "*Image/Sequence Comments", "img_seq_comments",
                $"Comments describing additional details about the image/sequence.{Environment.NewLine}" +
                $"If you selected the \"Multiple\" option from the Behaviour field, enter all the other Behaviours here.\").{Environment.NewLine}" +
                "e.g., \"Behaviour[Inspecting Camera,Travelling]\"",
                null),


            new(
                Control.FixedChoice, 1, "Unknown", "*Image Trigger Mode", "img_trig_mode",
                $"The trigger mode used to capture the image as reported in the image Exif data.{Environment.NewLine}" +
                $"Record \"Unknown\" if not known.{Environment.NewLine}" +
                $"Choose one from the drop down list provided.{Environment.NewLine}" +
                "e.g., \"Motion Detection\"",
                StandardsBase.CreateChoiceList(false, ["Motion Detection", "Time_ Lapse", "CodeLoc Not Entered", "External Sensor", "Unknown"])),


            new(
                Control.Note, 1, "", "*Image Sequence", "img_sequence",
                $"The order of the image in a rapid-fire sequence as reported in the image Exif data.{Environment.NewLine}" +
                $"Leave blank if not applicable.{Environment.NewLine}" +
                "e.g., \"1 of 3\"",
                null, copyable: false),


            new(
                Control.FixedChoice, 1, "", "*Image Infrared Illuminator", "img_infrared_illum",
                $"The Image Infrared Illuminator as reported in the image Exif data.{Environment.NewLine}" +
                $"Leave blank if not applicable.{Environment.NewLine}" +
                "e.g., \"On\"",
                StandardsBase.CreateChoiceList(true, ["On", "Off", "Unknown"])),


            new(
                Control.Note, 1, "", "*Image Flash Output", "img_flash",
                $"The Image Flash Output as reported in the image Exif data.{Environment.NewLine}" +
                $"Record the Image Flash Output as reported in the image Exif data.{Environment.NewLine}" +
                $"Record \"Unknown\" if not known; leave blank if not applicable.{Environment.NewLine}" +
                "e.g., \"Flash Did Not Fire\"",
                null),


            new(
                Timelapse.Constant.Control.DateTime_, 1,
                Timelapse.Util.DateTimeHandler.ToStringDatabaseDateTime(Timelapse.Constant.ControlDefault.DateTimeCustomDefaultValue),
                "Image/Sequence Date Time", "img_seq_date_time",
                $"The date and time of an image, or the image chosen to represent the sequence.{Environment.NewLine}" +
                "e.g., \"22-Jul-2018 11:02:02\"",
                null)

        ];
        #endregion
    }
}
