using System;
using System.Collections.Generic;
using System.Linq;
using Timelapse.Constant;
using Timelapse.Enums;

#pragma warning disable IDE1006 // Naming Style - we are using lower case names to match the json structure, we  mute the warning
namespace Timelapse.Recognition
{
    //[SuppressMessage("StyleCop.CSharp.NamingRules", "SA1300:ElementMustBeginWithUpperCaseLetter", Justification = "Reviewed.")]
    //#pragma warning disable SA1300 // ElementMustBeginWithUpperCaseLetter
    // This file contains four classes, which will hold image recognition information read in from the JSON file that follows the Microsoft Megadetector specification
    // - Recognizer
    // - info
    // - image
    // - detection

    /// <summary>
    /// The Recognizer class holds data produced by Microsoft's Megadetector
    /// Property names and structures follow the Microsoft Megadetetor JSON attribut names
    /// in order to allow the JSON data to be deserialized into the Recognizer data structure
    /// </summary>    
    public class Recognizer : IDisposable
    {
        #region Public Properties
        public info info { get; set; }
        public Dictionary<string, string> detection_categories { get; set; }
        public Dictionary<string, string> classification_categories { get; set; }
        public Dictionary<string, string> classification_category_descriptions { get; set; }
        public List<image> images { get; set; } = [];

        public List<(string Value, int Count)> DetectionDuplicates { get; set; } = [];
        public List<(string Value, int Count)> ClassificationDuplicates { get; set; } = [];
        #endregion

        #region Public Set Defaults
        // Defaults are just used when reading in current csv files, as that file does not include the category definitions
        // ReSharper disable once UnusedMember.Global
        public void SetDetectionCategoryDefaults()
        {
            detection_categories = new()
            {
                { RecognizerValues.NoDetectionCategory, RecognizerValues.EmptyDetectionLabel },
                { "2", "person" },
                { "4", "vehicle" }
            };
        }

        // Defaults are just used when reading in current csv files, as that file does not include the category definitions
        // ReSharper disable once UnusedMember.Global
        public void SetDetectionClassificationDefaults()
        {
            classification_categories = new()
            {
                { RecognizerValues.NoDetectionCategory, RecognizerValues.EmptyDetectionLabel },
            };
        }
        #endregion

        #region Public Methods
        // Returns true if the recognition data is compatible with Timelapse.
        // This is a (hopefully temporary) test to guard against files generated by AddaxAI outside of Timelapse,
        // as those files are problematic as the detection categories also includ classification categories,
        // which is not really compatible with how Timelapse uses classification categories as a distinct set of categories.
        // It is judged incompatible if the first classification category value matches any detection category value.
        // Note that this is a heuristic that depends on how AddaxAI adds classification categories to detection categories,
        // where the lowest numbered items are the actual detection categories with remaining numbered items being the classification categories.
        public RecognitionJsonCompatability IsRecognitionTimelapseCompatible()
        {
            //  1. If classification_categories is null or empty, returns true
            if (classification_categories == null || classification_categories.Count == 0)
            {
                return RecognitionJsonCompatability.Okay;
            }

            // 2.Sorts classification_categories by key and gets the first item's value       
            string firstClassificationValue = classification_categories
                .OrderBy(kvp => kvp.Key)
                .First()
                .Value;

            // 3. Steps through detection_categories sorted by key, comparing each value to that first classification category value
            // 4. Returns false if a match is found
            foreach (KeyValuePair<string, string> kvp in detection_categories.OrderBy(kvp => kvp.Key))
            {
                if (kvp.Value == firstClassificationValue)
                {
                    // 4. Returns false if a match is found,
                    return RecognitionJsonCompatability.AddaxAILikelyRanOutsideOfTimelapse;
                }
            }

            // 5. Check for duplicate categories.

            DetectionDuplicates = detection_categories.Values
            .GroupBy(v => v)                   // Group by the value string
            .Where(g => g.Count() > 1)         // Only keep values that appear more than once
            .Select(g => (g.Key, g.Count()))   // Create a tuple of (Value, Count)
            .ToList();

            if (classification_categories is not { Count: 0 })
            {
                ClassificationDuplicates = classification_categories.Values
                .GroupBy(v => v)                   // Group by the value string
                .Where(g => g.Count() > 1)         // Only keep values that appear more than once
                .Select(g => (g.Key, g.Count()))   // Create a tuple of (Value, Count)
                .ToList();
            }

            if (DetectionDuplicates is { Count: > 0 } || ClassificationDuplicates is { Count: > 0 })
            {
                return RecognitionJsonCompatability.CategoriesContainDuplicates;
            }

            // 6. Returns true as all is good
            return RecognitionJsonCompatability.Okay; ;
        }

        /// <summary>
        /// Identifies duplicate labels in detection and classification categories,
        /// keeps only the entry with the lowest numerical category number,
        /// and updates all image data to point to the kept category numbers.
        /// </summary>
        public void ResolveDuplicateCategories()
        {
            // 1. Generate remapping tables and clean up the dictionaries
            var detectionRemap = GetCategoryRemap(detection_categories);
            var classificationRemap = GetCategoryRemap(classification_categories);

            // 2. If no duplicates were found in either set, exit early to save processing time
            if (detectionRemap.Count == 0 && classificationRemap.Count == 0) return;

            // 3. Single-pass iteration through all images to update category numbers
            foreach (var image in images)
            {
                if (image.detections == null) continue;

                foreach (var detection in image.detections)
                {
                    // a) Update detection category number if it was a duplicate
                    if (detectionRemap.TryGetValue(detection.category, out string newDetCat))
                    {
                        detection.category = newDetCat;
                    }

                    // b) Update classification category numbers if they exist
                    if (classificationRemap.Count > 0 && detection.classifications != null)
                    {
                        foreach (var classification in detection.classifications)
                        {
                            // The category number is at index 0 of the Object[]
                            if (classification.Length > 0 && classification[0] != null)
                            {
                                string currentClassCat = classification[0].ToString();
                                if (currentClassCat != null && classificationRemap.TryGetValue(currentClassCat, out string newClassCat))
                                {
                                    classification[0] = newClassCat;
                                }
                            }
                        }
                    }
                }
            }
        }

        /// <summary>
        /// Identifies duplicate values in a category dictionary.
        /// Keeps the entry with the lowest numerical key, removes others from the dictionary,
        /// and returns a mapping from deleted keys to the kept key.
        /// </summary>
        private Dictionary<string, string> GetCategoryRemap(Dictionary<string, string> categories)
        {
            var remap = new Dictionary<string, string>();
            if (categories == null || categories.Count == 0) return remap;

            // Group by the label (Value) to find duplicates
            var duplicateGroups = categories
                .GroupBy(kvp => kvp.Value)
                .Where(g => g.Count() > 1)
                .ToList();

            foreach (var group in duplicateGroups)
            {
                // Sort keys numerically to find the "first" (lowest) category number
                var sortedKeys = group.Select(kvp => kvp.Key)
                    .OrderBy(k => int.TryParse(k, out int val) ? val : int.MaxValue)
                    .ThenBy(k => k) // fallback for non-numeric keys
                    .ToList();

                string primaryKey = sortedKeys[0];

                // Map all other keys in this group to the primary key
                for (int i = 1; i < sortedKeys.Count; i++)
                {
                    string oldKey = sortedKeys[i];
                    remap[oldKey] = primaryKey;

                    // Delete the duplicate entry from the original dictionary
                    categories.Remove(oldKey);
                }
            }

            return remap;
        }
        #endregion

        #region Disposing
        // Dispose implemented to follow pattern described in CA1816
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (disposing)
            {
                info = null;
                detection_categories = null;
                classification_categories = null;
                images = null;
            }
        }
        #endregion
    }

    /// <summary>
    /// The Info class holds extra information produced by Microsoft's Megadetector
    /// </summary>    
    public class info
    {
        #region Public Properties
        // The detector is a string that should include the detector filename, which will likely include
        // the detector verision in the form md_v*
        // for example the file name md_v4.1.0.pb says it used the megadetector version 5
        public string detector { get; set; }
        public string detection_completion_time { get; set; }
        public string classifier { get; set; }
        public string classification_completion_time { get; set; }
        public string format_version { get; set; }
        public detector_metadata detector_metadata { get; set; }
        public classifier_metadata classifier_metadata { get; set; }
        public string summary_report { get; set; }
        #endregion

        #region Public Set Defaults
        // Defaults are just used as needed
        public void SetInfoDefaults()
        {
            detector = RecognizerValues.DetectorUnknown;
            detection_completion_time = RecognizerValues.DetectionCompletionTimeUnknown;
            classifier = RecognizerValues.ClassifierUnknown;
            classification_completion_time = RecognizerValues.ClassificationCompletionTimeUnknown;
            format_version = RecognizerValues.FormatVersionUnknown;
            detector_metadata = new();
            classifier_metadata = new();
            summary_report = string.Empty;
        }
        #endregion
    }

    public class detector_metadata
    {
        // if its null, load it with some defaults
        // The megadetector_version is a string that provides detector version in the form md_v*
        // for example md_v5 is megadetector version 5
        public string megadetector_version { get; set; } = RecognizerValues.MDVersionUnknown;

        // typical_detection_threshold describes the typical bound of the maximum detection confidence
        // that normally produces a mostly correct result. For example, if it is .8, then the 
        // confidence range of .8 - 1 is a reasonable starting point for looking for mostly correct
        // detections
        public float? typical_detection_threshold { get; set; } = RecognizerValues.DefaultTypicalDetectionThresholdIfUnknown;

        // conservative_detection_threshold describes the lower bound of the maximum detection confidence
        // where results below that are likely mis-detections. For example, if it is .4, then anything less
        // than .4 is likely empty. Thus 'Empty' could be consider from 0 - .4
        public float? conservative_detection_threshold { get; set; } = RecognizerValues.DefaultConservativeDetectionThresholdIfUnknown;
    }

    public class classifier_metadata
    {
        // typical_classification_threshold describes the typical bound of the classification probability
        // that normally produces a mostly correct result. For example, if it is .75, then the 
        // a classification probability of .75 or higher is likely correct
        public float? typical_classification_threshold { get; set; } = RecognizerValues.DefaultTypicalClassificationThresholdIfUnknown;
    }

    /// <summary>
    /// The Image class holds information describing each image
    /// such as an ID, its file name, the max detection confidence, and a list of detections
    /// </summary>    
    public class image
    {
        #region Public Properties
        public long imageID { get; set; }
        public string file { get; set; } = string.Empty;

        // if frame_rate is not present for a video, just set it to a reasonable default frames/sec value.
        // it may be wrong, but its better than nothing.
        public float? frame_rate { get; set; } = 0;
        public List<detection> detections { get; set; } = [];

        #endregion
    }

    /// <summary>
    /// The Detection class holds information describing a single detection
    /// such as an ID, its category, its confidence, and the bounding box coordinates
    /// </summary>    
    public class detection
    {
        #region Public Properties
        public long detectionID { get; set; }
        public string category { get; set; } = string.Empty;
        public float conf { get; set; } = 0;

        //#pragma warning disable CA1819 // Properties should not return arrays. Reason: A Json serializer requires direct writing into an array property of this type.
        public double[] bbox { get; set; } = new double[4];
        //#pragma warning restore CA1819 // Properties should not return arrays

        public int frame_number { get; set; }

        public List<Object[]> classifications { get; set; } = [];

        #endregion

    }
}
