using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using Timelapse.Controls;
using Timelapse.Enums;
using Timelapse.QuickPaste;
using Timelapse.Util;

// A Partial class collecting the QuickPaste methods. 
namespace Timelapse
{
    public partial class TimelapseWindow
    {
        #region Method - Show / Hide / Terminate the QuickPaste window
        private void QuickPasteWindowShow()
        {
            if (this.quickPasteEntries == null)
            {
                return;
            }

            // If the quickpast window doesn't exist create it, and
            // add an event handler to it thatis used to generate events that identify the user action taken in that window
            if (this.quickPasteWindow == null || (!this.quickPasteWindow.IsLoaded))
            {
                // The quickPasteWindow hasn't been created yet, so do so.]
                // First, ensure that the saved window position fits within the screen, and reposition if needed.
                Rect windowRect = this.State.QuickPasteWindowPosition;
                // Height and Width should not be negative. There was an instance where it was, so this tries to catch it just in case
                windowRect.Height = Math.Abs(windowRect.Height);
                windowRect.Width = Math.Abs(windowRect.Width);
                windowRect = this.FitIntoASingleScreen(windowRect);
                this.State.QuickPasteWindowPosition = windowRect;

                // Now, create the window
                this.quickPasteWindow = new QuickPasteWindow()
                {
                    Owner = this,
                    QuickPasteEntries = this.quickPasteEntries,
                    Topmost = false,
                    WindowStartupLocation = WindowStartupLocation.Manual,
                    Position = this.State.QuickPasteWindowPosition,
                };

                // Add an event handler to capture events generated by the QuickPaste window
                this.quickPasteWindow.QuickPasteEvent += this.QuickPasteWindow_QuickPasteEvent;
            }

            // Finally, show the window if it makes sense to do so
            if (this.IsFileDatabaseAvailable() && this.DataHandler.FileDatabase.CountAllCurrentlySelectedFiles > 0)
            {
                this.quickPasteWindow.Show();
            }
        }

        // Terminate the QickPaste window
        private void QuickPasteWindowHide()
        {
            // If the quickpast window doesn't exist create it, and
            // add an event handler to it thatis used to generate events that identify the user action taken in that window
            if (this.quickPasteWindow != null && this.quickPasteWindow.IsLoaded)
            {
                this.quickPasteWindow.Hide();
                this.quickPasteWindow.Visibility = Visibility.Collapsed;
            }
        }

        private void QuickPasteWindowTerminate()
        {
            if (this.quickPasteWindow != null)
            {
                this.quickPasteWindow.Close();
                this.quickPasteWindow = null;
            }
        }
        #endregion

        #region Callbacks on Quickpast Event Type
        // The QuickPaste controls generate various events, depending on what the user selected.
        // Depending on the event received, perform the action indicated by the event by calling the appropriate method below
        private void QuickPasteWindow_QuickPasteEvent(object sender, QuickPasteEventArgs e)
        {
            switch (e.EventType)
            {
                case QuickPasteEventIdentifierEnum.New:
                    this.QuickPasteEntryNew();
                    break;
                case QuickPasteEventIdentifierEnum.Edit:
                    this.QuickPasteEntryEdit(e.QuickPasteEntry);
                    break;
                case QuickPasteEventIdentifierEnum.Delete:
                    this.QuickPasteEntryDelete(e.QuickPasteEntry);
                    break;
                case QuickPasteEventIdentifierEnum.MouseEnter:
                    this.QuickPasteDataControlsHighlight(e.QuickPasteEntry);
                    break;
                case QuickPasteEventIdentifierEnum.MouseLeave:
                    this.QuickPasteDataControlsUnHighlight(e.QuickPasteEntry);
                    break;
                case QuickPasteEventIdentifierEnum.Paste:
                    this.QuickPasteEntryPasteIntoDataControls(e.QuickPasteEntry, FlashEnum.FlashPreview);
                    break;
                case QuickPasteEventIdentifierEnum.ShortcutPaste:
                    this.QuickPasteEntryPasteIntoDataControls(e.QuickPasteEntry, FlashEnum.FlashBackground);
                    break;
                case QuickPasteEventIdentifierEnum.PositionChanged:
                    this.State.QuickPasteWindowPosition = this.quickPasteWindow.Position;
                    break;
                default:
                    break;
            }
        }
        #endregion

        #region Method - QuickPaste Entry: New / Delete / Edit
        // Create a quickpaste entry from the current data controls,
        // add it to the quickpaste entries, and update the display and the ImageSetTable database as needed
        private void QuickPasteEntryNew()
        {
            string title = "QuickPaste #" + (this.quickPasteEntries.Count + 1);
            QuickPasteEntry quickPasteEntry = QuickPasteOperations.TryGetQuickPasteItemFromDataFields(this.DataHandler.FileDatabase, this.DataHandler.ImageCache.CurrentRow, title);
            if (quickPasteEntry == null)
            {
                return;
            }

            // Make sure the quickPasteWindow is not topmost, as it may otherwise occlude part of the QuickPaste Editor
            if (this.quickPasteWindow.IsLoaded)
            {
                this.quickPasteWindow.Topmost = false;
            }
            QuickPasteEditor quickPasteEditor = new QuickPasteEditor(quickPasteEntry, this.DataHandler.FileDatabase, this.DataEntryControls)
            {
                Owner = this
            };
            if (quickPasteEditor.ShowDialog() == true)
            {
                quickPasteEntry = quickPasteEditor.QuickPasteEntry;
                if (this.quickPasteEntries == null)
                {
                    // This shouldn't be necessary, but just in case...
                    this.quickPasteEntries = new List<QuickPasteEntry>();
                }
                this.quickPasteEntries.Add(quickPasteEntry);
                this.QuickPasteRefreshWindowAndJSON();
            }

            // Restore the quickPaste window back to its topmost state
            if (this.quickPasteWindow.IsLoaded)
            {
                this.quickPasteWindow.Topmost = true;
            }
        }

        // Delete the quickPaste Entry from the quickPasteEntries
        private void QuickPasteEntryDelete(QuickPasteEntry quickPasteEntry)
        {
            this.quickPasteEntries = QuickPasteOperations.DeleteQuickPasteEntry(this.quickPasteEntries, quickPasteEntry);
            this.QuickPasteRefreshWindowAndJSON();
        }

        // Open the quickPaste Editor window
        private void QuickPasteEntryEdit(QuickPasteEntry quickPasteEntry)
        {
            if (quickPasteEntry == null)
            {
                return;
            }

            // Make sure the quickPasteWindow is not topmost, as it may otherwise occlude part of the QuickPaste Editor
            if (this.quickPasteWindow.IsLoaded)
            {
                this.quickPasteWindow.Topmost = false;
            }

            QuickPasteEditor quickPasteEditor = new QuickPasteEditor(quickPasteEntry, this.DataHandler.FileDatabase, this.DataEntryControls)
            {
                Owner = this
            };

            if (quickPasteEditor.ShowDialog() == true)
            {
                this.QuickPasteRefreshWindowAndJSON();
            }

            // Restore the quickPaste window back to its topmost state
            if (this.quickPasteWindow.IsLoaded)
            {
                this.quickPasteWindow.Topmost = true;
            }
        }
        #endregion

        #region Method Highlight / Unhighlight Control
        // Highlight the data controls affected by the Quickpaste entry
        private void QuickPasteDataControlsHighlight(QuickPasteEntry quickPasteEntry)
        {
            this.FilePlayer_Stop(); // In case the FilePlayer is going
            int row = this.DataHandler.ImageCache.CurrentRow;
            if (!this.DataHandler.FileDatabase.IsFileRowInRange(row))
            {
                return; // This shouldn't happen, but just in case...
            }

            foreach (QuickPasteItem item in quickPasteEntry.Items)
            {
                if (item.Use == false)
                {
                    continue;
                }

                // Find the data entry control that matches the quickPasteItem's DataLael
                foreach (KeyValuePair<string, DataEntryControl> pair in this.DataEntryControls.ControlsByDataLabel)
                {
                    DataEntryControl control = pair.Value;
                    if (control.DataLabel == item.DataLabel)
                    {
                        control.ShowPreviewControlValue(item.Value);
                    }
                }
            }
        }

        // Unhighlight the data controls affected by the Quickpaste entry
        private void QuickPasteDataControlsUnHighlight(QuickPasteEntry quickPasteEntry)
        {
            this.FilePlayer_Stop(); // In case the FilePlayer is going
            int row = this.DataHandler.ImageCache.CurrentRow;
            if (!this.DataHandler.FileDatabase.IsFileRowInRange(row))
            {
                return; // This shouldn't happen, but just in case...
            }

            foreach (QuickPasteItem item in quickPasteEntry.Items)
            {
                // If the item wasn't used, then it wasn't highlit.
                if (item.Use == false)
                {
                    continue;
                }

                // Find the data entry control that matches the quickPasteItem's DataLael
                foreach (KeyValuePair<string, DataEntryControl> pair in this.DataEntryControls.ControlsByDataLabel)
                {
                    DataEntryControl control = pair.Value;
                    if (control.DataLabel == item.DataLabel)
                    {
                        control.Container.ClearValue(Control.BackgroundProperty);
                        control.HidePreviewControlValue();
                        break;
                    }
                }
            }
        }
        #endregion

        #region Method Paste entry
        // Quickpast the given entry into the data control
        private void QuickPasteEntryPasteIntoDataControls(QuickPasteEntry quickPasteEntry, FlashEnum flash)
        {
            this.FilePlayer_Stop(); // In case the FilePlayer is going
            int row = this.DataHandler.ImageCache.CurrentRow;
            if (!this.DataHandler.FileDatabase.IsFileRowInRange(row))
            {
                return; // This shouldn't happen, but just in case...
            }

            foreach (QuickPasteItem item in quickPasteEntry.Items)
            {
                if (item.Use == false)
                {
                    continue;
                }

                // Find the data entry control that matches the quickPasteItem's DataLabel
                foreach (KeyValuePair<string, DataEntryControl> pair in this.DataEntryControls.ControlsByDataLabel)
                {
                    DataEntryControl control = pair.Value;
                    if (control.DataLabel == item.DataLabel)
                    {
                        // Changing a counter value does not trigger a ValueChanged event if the values are the same.
                        // which means multiple images may not be updated even if other images have the same value.
                        // To get around this, we set a bogus value and then the real value, which means that the
                        // ValueChanged event will be triggered. Inefficient, but seems to work.
                        if (this.IsDisplayingMultipleImagesInOverview() && control is DataEntryCounter counter)
                        {
                            counter.SetBogusCounterContentAndTooltip();
                        }

                        control.SetContentAndTooltip(item.Value);
                        if (flash == FlashEnum.FlashPreview)
                        {
                            control.FlashPreviewControlValue();
                        }
                        else
                        {
                            control.FlashContentControl();
                        }
                        break;
                    }
                }
            }
        }
        #endregion

        #region Refresh Quickpaste Refresh Window and JSON
        // Update the Quickpaste JSON in the ImageSetTable and refresh the Quickpaste window to reflect the current contents
        private void QuickPasteRefreshWindowAndJSON()
        {
            this.DataHandler.FileDatabase.ImageSet.QuickPasteAsJSON = JsonConvert.SerializeObject(this.quickPasteEntries);
            this.DataHandler.FileDatabase.UpdateSyncImageSetToDatabase();
            if (this.quickPasteWindow != null)
            {
                this.quickPasteWindow.Refresh(this.quickPasteEntries);
            }
        }
        #endregion
    }
}
